Article : Personnalisation du serveur
discordfr/wiki pull request #104
Opened 2021-08-04 09:07 UTC by PetitPotiron

**Quel est votre identifiant Discord ?**<br/> 
715826047949471785

**Décrivez rapidement vos ajouts ou changements**<br/>
- Comment et pourquoi personnaliser son serveur
- Icône de serveur, nom de serveur, salons AFK, salons de messages système et paramètres de notification par défaut

2021-08-05 17:16 UTC, DanaliethPantheus requested changes

2021-08-05 17:16 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +Pour désactiver tous les messages système, il faut choisir l'option `Pas de messages système` dans le menu déroulant pour choisir le salon de notifications système. Pour ne désactiver  ou n'activer q
Espace en trop après "pour ne désactiver"
Pas de s à "messages système"

2021-08-05 17:16 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +![Réglage des apramètres de notification par défaut](https://user-images.githubusercontent.com/70655051/128153811-ddd18695-2f6d-4583-9a5f-2811f170e1b8.png)
**para**mètres et pas apramètres

2021-08-18 17:42 UTC, PetitPotiron reviewed
Merci de cette relecture attentive, j'ai corrigé toutes les erreurs !

2021-08-19 08:17 UTC, DanaliethPantheus requested changes

2021-08-19 08:17 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +Pour désactiver tous les messages système, il faut choisir l'option `Pas de messages système` dans le menu déroulant pour choisir le salon de notifications système. Pour ne désactiver ou n'activer qu
[...] dans **la liste déroulante** **dans lequel on choisit** le salon de notifications système.

2021-08-19 08:17 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +Pour désactiver tous les messages système, il faut choisir l'option `Pas de messages système` dans le menu déroulant pour choisir le salon de notifications système. Pour ne désactiver ou n'activer qu
La suite fait peut-être un peu trop tutoriel ?

2021-08-19 08:17 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +La gestion du nom d'un serveur se fait dans la catégorie `Vue d'ensemble` des paramètres de celui-ci. Il est alors possible de changer le nom du serveur (dont la longueur est supérieure à 1 caractère
> remplacer "paramètres de celui-ci" par "paramètres du serveur" pour plus de clarté

2021-08-19 08:17 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +![Réglage des apramètres de notification par défaut](https://user-images.githubusercontent.com/70655051/128153811-ddd18695-2f6d-4583-9a5f-2811f170e1b8.png)
> **para**mètres et pas apramètres

2021-08-19 08:17 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +Les paramètres de notification par défaut sont la manière dont les utilisateurs vont recevoir une notification. Lors de la création d'un serveur, les notifications sont réglées sur `Tous les messages
[...] en recevront une à chaque message [...] 
--> supprimer _ou non_

2021-08-19 08:17 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +Les paramètres de notification par défaut sont la manière dont les utilisateurs vont recevoir une notification. Lors de la création d'un serveur, les notifications sont réglées sur `Tous les messages
[...] en recevront une à chaque message [...] 
--> supprimer _ou non_

2021-08-19 08:17 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +Les paramètres de notification par défaut sont la manière dont les utilisateurs vont recevoir une notification. Lors de la création d'un serveur, les notifications sont réglées sur `Tous les messages
[...] il est recommandé **de** choisir l'option

2021-08-19 08:17 UTC, DanaliethPantheus commented on configuration-serveur/configuration-serveur/personnalisation.md
> +Les paramètres de notification par défaut sont la manière dont les utilisateurs vont recevoir une notification. Lors de la création d'un serveur, les notifications sont réglées sur `Tous les messages
[...] qui n'ont pas réglé leurs paramètres de notification [...]
--> enlever le _s_ de **notification**

2021-08-20 19:12 UTC, PetitPotiron reviewed
Merci encore pour votre assiduité à tous!
J'ai aussi modifié quelques expressions qui, à mon goût, n'étaient pas assez claires.

2021-08-29 18:46 UTC, areyouokevan requested changes
Il faudrait que tu remplaces les screenshots par ceux que j'ai fournis. Tu peux y effectuer quelques modifications comme re-ajouter les encadrer rouge qu'il y avait avant. Mais pas de cropping.

Je pense que pour améliorer la clarté de ton article tu devrais merge (mettre ensemble) l'ajout, la modification et la suppression de l'icône du serveur.

2021-08-29 18:46 UTC, areyouokevan commented on configuration-serveur/configuration-serveur/personnalisation.md
> +### Supprimer l'icône
Supprimer l'icône peut être merge avec ajouter un icône et modifier.

2021-08-29 18:46 UTC, areyouokevan commented on configuration-serveur/configuration-serveur/personnalisation.md
> +### Modifier l'icône
Modifier l'icône peut être merge avec ajouter l'icône.

2021-08-29 18:46 UTC, areyouokevan commented on configuration-serveur/configuration-serveur/personnalisation.md
> +![Choisir le salon AFK](https://user-images.githubusercontent.com/70655051/128147994-3a3f4ab8-38cd-4d59-abf5-809d4b19db7f.png)
Remplacer le screenshot par https://i.discord.fr/Leyw.png

2021-08-29 18:46 UTC, areyouokevan commented on configuration-serveur/configuration-serveur/personnalisation.md
> +![Choisir la durée d'inactivité](https://user-images.githubusercontent.com/70655051/128148578-38ac75ff-1339-4cd6-9317-c3e9a0e6adf4.png)
Remplacer le screenshot par https://i.discord.fr/vQOX.png

2021-08-29 18:46 UTC, areyouokevan commented on configuration-serveur/configuration-serveur/personnalisation.md
> +![Activation ou désactivation des messages système](https://user-images.githubusercontent.com/70655051/128152445-05b22076-ec43-405d-a3eb-0f125a7ca372.png)
Remplacer le screenshot par https://i.discord.fr/68RR.png

2021-08-29 18:46 UTC, areyouokevan commented on configuration-serveur/configuration-serveur/personnalisation.md
> +![Réglage des paramètres de notification par défaut](https://user-images.githubusercontent.com/70655051/128153811-ddd18695-2f6d-4583-9a5f-2811f170e1b8.png)
Remplacer le screenshot par https://i.discord.fr/JvIn.png

2021-09-05 09:59 UTC, IchiiDev requested changes
Avant toute correction, merci de changer les images comme demandé !

2021-09-05 17:10 UTC, PetitPotiron commented
> 
> 
> Avant toute correction, merci de changer les images comme demandé !

Je m'en occupe, je n'ai pas eu beaucoup de temps en ce moment à cause de la rentrée... 👍

2021-09-08 16:27 UTC, PetitPotiron reviewed
Merci beaucoup à tous-tes, j'ai finalisé l'article, je crois que tout y est 🐢.

2021-10-09 16:26 UTC, PetitPotiron commented
Merci encore pour tout votre travail, je n'ai pas aperçu d'autres imperfections 👀. Je pense sincèrement que l'article est fin prêt, bonne soirée,
Moonrise

2021-10-25 15:16 UTC, merged