Update banniere.md
discordfr/wiki pull request #105
Opened 2021-08-05 13:25 UTC by JustFox222

Modification de l'article : Changement de la mise en page / explications des deux possibilités de l'option bannière (images couleurs).

**Quel est votre identifiant Discord ?**<br/> 
768754414814625822

**Décrivez rapidement vos ajouts ou changements**<br/>
Changements de la mise en page / explications des deux possibilités de l'option bannière (Images Couleurs)

2021-08-05 14:17 UTC, DanaliethPantheus requested changes

2021-08-05 14:17 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/banniere.md
> +En tant que propriétaire du compte en question, l'option se trouve dans le deuxième onglet ("Profil d'utiliseur") des les paramètres d'utilisateur. Il est possible si l'utilisateur possède un abonnem
Profil d'utili**sa**teur (et pas _utiliseur_)

L'abonnement "Nitro Boost" n'existe pas. C'est l'abonnement Nitro, par opposition au Nitro Classic. Les boosts de serveurs sont des bonus de niveau, mais ce n'est pas le boost en lui-même qui offre la possibilité de mettre une image personnalisée. C'est seulement le type d'abo (Nitro/Nitro Classic)

Mettre une virgule après _l'utilisateur peut_ et _souhaite,_ et contracter _si il_ en _s'il_.

2021-08-05 14:17 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/banniere.md
> -La bannière de profil est accessible uniquement aux utilisateurs titulaires d'un nitro boost. Le nitro classic n'inclut pas la bannière de profil.
Pas "Nitro Boost" mais "abonnement Nitro".
Rajouter les majuscules à Nitro Classic.

2021-08-05 14:17 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/banniere.md
> +La bannière sur Discord est une image qui peut être personnalisée et qui s'affiche au dessus du profil d'un utilisateur. Cela peut être une image (statique ou animée) ou une couleur par défaut ou déf
au-dessus (avec le trait d'union entre les deux mots)

2021-08-05 14:17 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/banniere.md
> -- Cliquer sur le bouton "Profil d'utilisateur".
**onglet** "Profil d'utilisateur" à la place de bouton.

2021-08-05 14:17 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/banniere.md
> +En tant que propriétaire du compte en question, l'option se trouve dans le deuxième onglet ("Profil d'utiliseur") des les paramètres d'utilisateur. Il est possible si l'utilisateur possède un abonnem
Des les paramètres = des paramètres

2021-08-05 23:59 UTC, grifgrif requested changes
Coucou JustFox!

Tu peut étoffer l'article en y promenant quelques petites images et ajustements.
Pense à préciser ou on vois les bannières (**pop-up au click dans la liste des membres** & sur le profil de l'utilisateur).

La taille ne fais pas tutoriel et tu peut la préciser sans dommage dans cette page, mais pense à la présenter, par exemple au début ("La bannière est une image d'au moins 600x240px ...").
Précise aussi ce qui arrive à la bannière à la fin de l'abonnement.
C'est le genre d'informations que les gens recherchent.

Sinon très bien!

2021-08-05 23:59 UTC, grifgrif commented on parametres-compte/personnalisation-compte/banniere.md
> -![Discord  Bannière](https://i.discord.fr/oZe.png)
Le retrait de cette image n'est pas obligatoire, elle peut être bien.
Vous pouvez essayer aussi de montrer l'option comme ci-joint pour colorer la lecture: 

![Exemple à ne pas user](https://i.discord.fr/RPt.png)

2021-08-05 23:59 UTC, grifgrif commented on parametres-compte/personnalisation-compte/banniere.md
> +La bannière sur Discord est une image qui peut être personnalisée et qui s'affiche au dessus du profil d'un utilisateur. Cela peut être une image (statique ou animée) ou une couleur par défaut ou déf
> au-dessus (avec le trait d'union entre les deux mots)

C'est à corriger, oui.

2021-08-05 23:59 UTC, grifgrif commented on parametres-compte/personnalisation-compte/banniere.md
> -La bannière de profil est accessible uniquement aux utilisateurs titulaires d'un nitro boost. Le nitro classic n'inclut pas la bannière de profil.
> Pas "Nitro Boost" mais "abonnement Nitro".
> Rajouter les majuscules à Nitro Classic.

Effectivement, Discord appelle son "nitro boost" le Nitro et son ancien Nitro le "Nitro Classic".
Vous pouvez utiliser les notes dans la page de wiki pour préciser la taille maximale du fichier, garde le coté tutoriel loin en rédigeant cette note.

2021-08-05 23:59 UTC, grifgrif commented on parametres-compte/personnalisation-compte/banniere.md
> +En tant que propriétaire du compte en question, l'option se trouve dans le deuxième onglet ("Profil d'utiliseur") des les paramètres d'utilisateur. Il est possible si l'utilisateur possède un abonnem
> Profil d'utili**sa**teur (et pas _utiliseur_)
> 
> L'abonnement "Nitro Boost" n'existe pas. C'est l'abonnement Nitro, par opposition au Nitro Classic. Les boosts de serveurs sont des bonus de niveau, mais ce n'est pas le boost en lui-même qui offre la possibilité de mettre une image personnalisée. C'est seulement le type d'abo (Nitro/Nitro Classic)
> 
> Mettre une virgule après _l'utilisateur peut_ et _souhaite,_ et contracter _si il_ en _s'il_.

DanaliethPantheus est juste.



> Des les paramètres = des paramètres

À corriger aussi.

2021-08-09 11:16 UTC, MaxenceGu21 commented on parametres-compte/personnalisation-compte/banniere.md
> +## Dimentions de la bannière de profil
Faute d'orthographe: **Dimensions**.

2021-08-09 11:16 UTC, MaxenceGu21 commented on parametres-compte/personnalisation-compte/banniere.md
> +La bannière sur Discord est une image qui mesure 600xp en longueur et 240xp en largeur pour que discord ne refuse pas votre bannière.
Cette phrase ne va pas pour deux raisons: **Des éléments sont feux** / **Vous vous adressez à quelqu'un alors que vous devez adopter une réaction neutre**.

Préférez mettre cette phrase: **"Il est recommandé de mettre une image de 600 x 240."** --> Ce n'est pas obligatoire mais recommandé et Discord ne refuse pas l'image si elle n'est pas en 600 x 240.

2021-08-13 20:19 UTC, grifgrif requested changes
Coucou,
Tout est bon,
Juste l'image a refaire, tu peut user le salon #demande-image pour demander une image.
Après il manque un passage dans #relecture est on es bon !

2021-08-13 20:19 UTC, grifgrif commented on parametres-compte/personnalisation-compte/banniere.md
> +![Capture d’écran 2021-08-09 110039](https://user-images.githubusercontent.com/72766562/128683789-4a80460a-2808-468c-bd1a-072090e2c0a6.jpg)
C'est pas très explicite mais dans le markdown mon image se nomme
![Image Démostrative](https://i.discord.fr/rqb.png)

2021-09-03 15:34 UTC, grifgrif approved these changes
Bonjour à toi,
C'est validé!
Merci pour ta contribution!

2021-09-03 15:36 UTC, merged