Update profil.md
discordfr/wiki pull request #106
Opened 2021-08-05 19:18 UTC by MaxenceGu21

**Modification de l'article:**
- Revue de la mise en page / Mise à jour du profil.

**Quel est votre identifiant Discord ?**<br/> 
864423158806347796

**Décrivez rapidement vos ajouts ou changements**<br/>
- Mise à jour des profils sur Discord.
- Revue rapide de la mise en page.

2021-08-05 21:03 UTC, MaxenceGu21 commented
**Note importante:**
- Le screen mit avec les chiffres sera à modifier impérativement. A titre personnel, je n'ai pas de logiciel numérique pour faire ce genre de chose donc je fais tout à la main.

2021-08-06 12:55 UTC, DanaliethPantheus requested changes
Corrections orthographe et tournures de phrases + Suggestions modifications diverses

2021-08-06 12:55 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/profil.md
> +- **4:** Le nom du compte est un pseudo contenant un discriminateur à 4 chiffres (ici ChanceSphere574#1537), ce discriminateur est unique et personne ne peut avoir les 4 mêmes chiffres sauf si le pro
Le discriminateur n'est _pas unique_, seule l'ID est unique. Le discriminateur est **aléatoire** (sauf quand on a Nitro et qu'on le modifie, mais il redevient aléatoire quand on n'a plus d'abonnement Nitro).
Du coup, ce n'est pas juste de dire que personne ne peut avoir les 4 mêmes chiffres (sinon il n'y aurait que 9999 personnes sur Discord, le discriminateur #0000 n'étant pas accessible).

2021-08-06 12:55 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/profil.md
> +- **5:** Le [statut personnalisé](https://discord.fr/wiki/parametres-compte/personnalisation-compte/statuts-personnalise/) est un élément défini par l'utilisateur qui s'affiche lorsqu'il est en ligne
Pas uniquement En ligne, mais Inactif ou Ne pas déranger aussi ! 
Le statut personnalisé s'affiche quand l'utilisateur n'est _pas Invisible_.

2021-08-06 12:55 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/profil.md
> +- **7:** Le "A propos de moi" est un élément défini par l'utilisateur, tout comme le statut personnalisé, en revanche, même si il est hors ligne, cet élément ne disparaît pas.
Commencer une nouvelle phrase à "En revanche" ?
[...] même **s'il** hors ligne **ou invisible** [...]

2021-08-06 12:55 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/profil.md
> +- **8:** Les notes sont privées, uniquement visible par vous-même; elles peuvent être modifiées à tout moment.
uniquement visible**s**

2021-08-06 12:55 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/profil.md
> +- **4:** Le nom du compte est un pseudo contenant un discriminateur à 4 chiffres (ici ChanceSphere574#1537), ce discriminateur est unique et personne ne peut avoir les 4 mêmes chiffres sauf si le pro
Peut-être préciser que le discriminateur est toujours précédé d'un # (ce qui fait qu'on l'appelle Discord tag, d'ailleurs).

En fait, je trouve qu'on comprend mieux l'ancienne définition : 
**2.** Le nom de compte Discord est composé d'un pseudo et d'un discriminateur de 4 chiffres (ici Discord#0000). Ce dernier est généré aléatoirement à la création du compte mais peut être personnalisé si l'on possède Nitro.

Il suffit juste de réadapter l'exemple pour correspondre avec le nouveau pseudo. Mais celui de ChanceSphere est un peu compliqué, parce qu'il y a des chiffres avant, après... Ca n'aide pas forcément à la compréhension ^^

2021-08-06 12:55 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/profil.md
> +- **6:** Les boutons de navigation permettent d'avoir plus d'informations concernant l'utilisateur en question (ici son activité actuelle, les serveurs ainsi que les amis en communs).
Boutons de navigation ou **onglets** de navigation ?

2021-08-06 13:13 UTC, MaxenceGu21 commented on parametres-compte/personnalisation-compte/profil.md
> +- **4:** Le nom du compte est un pseudo contenant un discriminateur à 4 chiffres (ici ChanceSphere574#1537), ce discriminateur est unique et personne ne peut avoir les 4 mêmes chiffres sauf si le pro
✅ Remise à la phrase de base: "Le nom de compte Discord est composé d'un pseudo et d'un discriminateur de 4 chiffres (ici ChanceSphere574#1537). Ce dernier est généré aléatoirement à la création du compte mais peut être personnalisé si l'on possède Nitro.". 🔽

- Celle-ci sera modifiée lorsque qu'un autre screen arrivera.

2021-08-06 13:14 UTC, MaxenceGu21 commented on parametres-compte/personnalisation-compte/profil.md
> +- **5:** Le [statut personnalisé](https://discord.fr/wiki/parametres-compte/personnalisation-compte/statuts-personnalise/) est un élément défini par l'utilisateur qui s'affiche lorsqu'il est en ligne
✅ Corrigé.

2021-08-06 13:14 UTC, MaxenceGu21 commented on parametres-compte/personnalisation-compte/profil.md
> +- **7:** Le "A propos de moi" est un élément défini par l'utilisateur, tout comme le statut personnalisé, en revanche, même si il est hors ligne, cet élément ne disparaît pas.
✅ Corrigé.

2021-08-06 13:15 UTC, MaxenceGu21 commented on parametres-compte/personnalisation-compte/profil.md
> +- **8:** Les notes sont privées, uniquement visible par vous-même; elles peuvent être modifiées à tout moment.
✅ Corrigé.

2021-08-06 13:15 UTC, MaxenceGu21 commented on parametres-compte/personnalisation-compte/profil.md
> +- **6:** Les boutons de navigation permettent d'avoir plus d'informations concernant l'utilisateur en question (ici son activité actuelle, les serveurs ainsi que les amis en communs).
✅ Corrigé.

2021-08-08 14:58 UTC, LukeSkywalkerDev commented on parametres-compte/personnalisation-compte/profil.md
> +- **3:** Les [badges de profil](https://discord.fr/wiki/programmes-communautaires/outils-communautaires/badges/) sont la preuve d'appartenance à un programme communautaire de Discord ou d'implication
Dans la phrase "[...] la preuve d'appartenance à un programme communautaire de Discord ou d'implication d'un utilisateur sur Discord." : 
 - Peut-être serait-il intéressant de mettre le connecteur logique "et" au lieu du "ou" actuel, puisque la première partie est en corrélation avec la seconde.
 -  Remplacer le dernier mot de la phrase ("Discord") par "cette plateforme" afin d'éviter les répétitions.

2021-08-08 14:59 UTC, MaxenceGu21 commented on parametres-compte/personnalisation-compte/profil.md
> +- **3:** Les [badges de profil](https://discord.fr/wiki/programmes-communautaires/outils-communautaires/badges/) sont la preuve d'appartenance à un programme communautaire de Discord ou d'implication
✅ Corrigé.

2021-09-05 10:00 UTC, merged