Create  À propos de moi.md
discordfr/wiki pull request #107
Opened 2021-08-06 12:16 UTC by Itskleii

**Quel est votre identifiant Discord ?**<br/> 
Entrez votre ID ici 558708062702141469

**Décrivez rapidement vos ajouts ou changements**<br/>
Entrez votre description ici J'ai expliqué ce que c'était le " À  propos de moi " et comment le modifier.

2021-08-06 13:43 UTC, Karal0001 commented
Bonjour,

Merci de détaillé un peu plus votre page et de mettre des images pertinentes en évitant de faire apparaitre un nom d'utilisateur (ex: La section profil d'utilisateur sur ordinateur puis téléphone)

2021-08-06 14:36 UTC, MaxenceGu21 commented
Bonjour,

Après lecture de votre article, faites attention au fait d'adopter une réaction neutre. Préférez dire "dans les paramètres d'utilisateur" plutôt que "dans vos paramètres d'utilisateur". Ne vous adressez pas aux lecteurs.

2021-08-06 23:04 UTC, grifgrif requested changes
Bonjour Itskleii,

L'article est un très bon début mais pas encore assez étoffé.

Discord.fr n'est pas un tutoriel mais un wiki. Il faut donc mettre de coté toute mention directe à l'utilisateur "vous, tu, nous, etc..." et le coté _tutoriel_ qui se dégage de vos écrits.

Vous pouvez aussi étoffer en présentant plus d'exemples de markdown (voir image), il est aussi conseillé de préciser le nombre de caractères et ce qui n'est pas accepté selon le règlement de Discord (NSFW, liens vers des scams, etc...). 

---

![Exemple à ne pas copier ni intégrer](https://i.discord.fr/QLq.png)

---

N'oubliez pas que ce n'est certes pas un tutoriel mais vous devez passer par les fondamentaux et expliquer très clairement ce que c'est, vous pouvez même décrire la page d'option en indiquant (et liant à nos autres articles) les options adjointes et ou pouvons-nous trouver ce texte. (profil & **pop-up dans la liste des utilisateurs**)
Vous pouvez aussi ajouter par exemple la date d'ajout sur Discord.

Une correction de la formulation doit être faite pour permettre une lecture claire.

Merci encore pour cette page, bon travail!
Je viendrai voir une fois les changements faits ^^.

2021-08-13 20:36 UTC, grifgrif requested changes
Coucou,
Une petite modification, une relecture orthographique par les contributeurs et on est bon !

2021-08-13 20:36 UTC, grifgrif commented on parametres-compte/personnalisation-compte/À propos de moi.md
> +![image](https://user-images.githubusercontent.com/84471738/129167696-05dee2e7-fb28-4615-abba-83a3247864ca.png)
Mes images de commentaire ne sont pas destinés à utilisation directe, vous pouvez user du salon #demande-image en temps que contributeur ou vous pouvez demander à un contributeur.

2021-09-03 15:51 UTC, grifgrif requested changes
Bonjour Itskleii!
Un peu de remise au normes, de reformulation, une relecture est on est bon pour la publication!
Merci d'avance 😄!

2021-09-03 15:51 UTC, grifgrif commented on parametres-compte/personnalisation-compte/À propos de moi.md
> +Discord a ajouté la possibilité de pouvoir customiser son [profil](https://discord.fr/wiki/parametres-compte/personnalisation-compte/profil/) et de rajouter plus d'informations sur soi-même. L'utilis
"Discord a ajouté la possibilité de"
->
"Sur Discord il est possible de"
Ce n'est pas un article, gardez le présent.

2021-09-03 15:51 UTC, grifgrif commented on parametres-compte/personnalisation-compte/À propos de moi.md
> +Mais attention, il y a une limite de 190 caractères, et les [Termes](https://dfr.gd/terms) ainsi que les [Guidelines](https://dfr.gd/guidelines) de Discord sont à respecter.
"et les [Termes](https://dfr.gd/terms) ainsi que les [Guidelines](https://dfr.gd/guidelines) de Discord sont à respecter."
Bien de rappeler mais c'est super logique, à reformuler.

2021-09-15 10:48 UTC, PetitPotiron commented on parametres-compte/personnalisation-compte/À propos de moi.md
> +Sur Discord, il est possible de customiser son [profil](https://discord.fr/wiki/parametres-compte/personnalisation-compte/profil/) et de rajouter plus d'informations sur soi-même. L'utilisateur a la
"tout le texte qu'on souhaite. " Il est nécessaire de préciser qu'il y a quand même une limite de caractères.

2021-09-15 10:49 UTC, PetitPotiron commented on parametres-compte/personnalisation-compte/À propos de moi.md
> +Sur Discord, il est possible de customiser son [profil](https://discord.fr/wiki/parametres-compte/personnalisation-compte/profil/) et de rajouter plus d'informations sur soi-même. L'utilisateur a la
"customiser" est un anglicisme, je pense qu'il est plus clair d'utiliser "personnaliser".

2021-09-15 11:02 UTC, PetitPotiron requested changes
Certains changements restent nécessaire à mon goût.

2021-09-15 11:02 UTC, PetitPotiron commented on parametres-compte/personnalisation-compte/À propos de moi.md
> +Sur Discord, il est possible de customiser son [profil](https://discord.fr/wiki/parametres-compte/personnalisation-compte/profil/) et de rajouter plus d'informations sur soi-même. L'utilisateur a la
"et tout le texte qu'on souhaite." ce texte porte à confusion avec la ligne d'après, expliquant qu'il y a une limite de caractères.

2021-09-15 11:02 UTC, PetitPotiron commented on parametres-compte/personnalisation-compte/À propos de moi.md
> +Sur Discord, il est possible de customiser son [profil](https://discord.fr/wiki/parametres-compte/personnalisation-compte/profil/) et de rajouter plus d'informations sur soi-même. L'utilisateur a la
Je préciserais à quoi sert la syntaxe markdown : 
`et d'utiliser la syntaxe [Markdown](https://discord.fr/wiki/interface/salon-textuel/markdown/) pour mettre en forme le texte.`

2022-02-22 23:01 UTC, IchiiDev commented
Après revérification, la PR avait été fermée afin de faire appliquer les règles de contribution:
Merci de ne pas créer de fichier directement et de demander l'approbation de l'équipe avant toute chose en ouvrant une Issue.

2022-02-22 23:01 UTC, closed without merging