Update statistiques-serveur.md
discordfr/wiki pull request #108
Opened 2021-08-07 13:53 UTC by LukeSkywalkerDev

**Décrivez rapidement vos ajouts ou changements**<br/>

Rédaction de l'article statistiques-serveur.md

Sources : 
 - L'interface Discord et le site https://discord.com/developers/servers/
 - https://discord-france.fr/les-statistiques-de-serveurs-discord/  

Je n'ai pas ajouté d'images concernant la page précise de statistiques parce que je n'ai pas accès aux Analyses du serveur discord.fr (je pense que cela aurait été hors-sujet de mettre les analyses d'un autre serveur). 

Bonne relecture :p

2021-08-07 15:38 UTC, grifgrif requested changes
Bonjour LukeSkywalkerDev,

Merci de cet article de qualité.

Encore quelques fautes de mots et de syntaxe.
Beaucoup de tournures de phrases sont encore hésitantes ou à revoir.
Je pense que tu devrai te relire attentivement avant de poster.

Prends en sources des articles anglais officiels est la meilleure chose à faire, tu peut aussi poser des questions à la communauté.

Oublie pas de rester en dehors du tutoriel, n'hésite pas à demander à la communauté ou aux contributeurs si tu n'arrive pas à trouver ta phrase. Il serons content de t'aider !

Merci encore et on se revois une fois les changements faits !

2021-08-07 15:38 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Il est possible de s'y rendre depuis les **Paramètres de serveur**, dans l'onglet **Analyses de serveur** de la partie **Communauté**.
Trop tutoriel, utilisez plutôt "Vous trouverez cette option dans vos paramètres de serveur".

2021-08-07 15:38 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +![Onglet - Menu - Analyses de Serveur](https://i.discord.fr/gmI.png)
Si vous faites une image, préférer une image d'ensemble.

---


![Ne pas utiliser](https://i.discord.fr/moT.png)

2021-08-07 15:38 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Discord affichera un lien sur lequel il faut cliquer pour accéder à la page des statistiques. Ce lien a la forme `https://discord.com/developers/servers/idDuServeur/analytics/`.
En reformulant, prévenez que les statistiques sont hébergés sur un site et en dehors de l'application.

> https://discord.com/developers/servers/**idDuServeur**/analytics/

Dites plutôt "{Identifiant du serveur}".

2021-08-07 15:38 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> + - Du nombre de nouveaux utilisateurs discutant et d'utilisateurs discutant.
À reformuler.

2021-08-07 15:38 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> + - La proportion de personnes ayant cliqué sur tel ou tel item ainsi que la proportion de mebres ayant par la suite envoyé un message.
> la proportion de **mebres** ayant

"membres"
ne pas dire "item" mais "option"; Ou vous pouvez reformuler.

2021-08-07 15:38 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Désignant le [programme partenaire de Discord](https://discord.fr/wiki/programmes-communautaires/partenariat/serveur/), cet onglet permet d'accéder soit à l'activité du serveur requise par rapport au
À reformuler.
Trop de répétitions.

2021-08-07 15:38 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Les **Analyses de Serveur** permettent d'accéder à de nombreuses statistiques afin d'améliorer l'activité du serveur. On accède notamment à la croissance du serveur, l'engagement (textuel et vocal) d
> son statut par rapport au programme partenaire.

Le statut du serveur.

2021-08-07 16:28 UTC, LukeSkywalkerDev commented
Salut,

J'ai effectué les modifications demandées et reformulé un certain nombre de passages ainsi que de tournures mal formulées, difficile à comprendre ou encore trop vagues.
Je suis assez à l'aise dans la rédaction, donc je ne mets pas trop de temps pour trouver ma phrase :p (d'autant plus qu'il ne s'agit pas de mon premier article haha)

Voili voilou, je te laisse vérifier une nouvelle fois !

2021-08-08 00:47 UTC, grifgrif requested changes
Bonjour LukeSkywalkerDev,

Merci pour ce très bon article.

Encore quelques détails et on est bon!

Merci encore pour ton activité ici ^^.

2021-08-08 00:47 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> + - La proportion de personnes ayant cliqué sur tel ou tel optionainsi que celle ayant par la suite envoyé un message.
Encore un peu confus.

2021-08-08 00:47 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Afin de permettre à ses utilisateurs d'accéder à de plus amples informations concernant l'actibité des serveurs aux gérants de ces derniers, Discord propose un service d'analyse et de statistiques dé
> concernant l'actibité des serveurs

Un peu de correction ^^

2021-08-08 00:47 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Discord affichera un lien sur lequel il faut cliquer pour accéder à la page des statistiques. Ce lien a la forme `https://discord.com/developers/servers/identifiant-du-serveur/analytics/`.
Casse le lien, met quelque chose que les gens remarque, n'hésite pas à mettre le truc en gras/italique.

2021-08-08 06:29 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Afin de permettre à ses utilisateurs d'accéder à de plus amples informations concernant l'actibité des serveurs aux gérants de ces derniers, Discord propose un service d'analyse et de statistiques dé
OMG c'est corrigé

2021-08-08 06:38 UTC, LukeSkywalkerDev commented
Hello,

Toutes les modifications demandées ont été réalisées. 
(Btw tu peux simplement m'appeler Luke)

2021-08-08 10:31 UTC, DanaliethPantheus requested changes

2021-08-08 10:31 UTC, DanaliethPantheus commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Ces dernières, particulièrement précises -notamment pour les serveurs de plus de 500 membres-, présente à travers plusieurs onglets, graphiques et chiffres l'activité du serveur et de ses membres, l'
remplacer le **trait d'union** par un tiret demi-cadratin (–) et mettre des **espaces** avant et après les tirets (sauf le dernier, avant la virgule, qui n'a pas besoin d'un tiret après)

2021-08-08 10:31 UTC, DanaliethPantheus commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Ces dernières, particulièrement précises -notamment pour les serveurs de plus de 500 membres-, présente à travers plusieurs onglets, graphiques et chiffres l'activité du serveur et de ses membres, l'
[...] présent**ent** à travers plusieurs [...]

2021-08-08 10:31 UTC, DanaliethPantheus commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Ces dernières, particulièrement précises -notamment pour les serveurs de plus de 500 membres-, présente à travers plusieurs onglets, graphiques et chiffres l'activité du serveur et de ses membres, l'
Je n'ai pas compris la parenthèse "(ou davantage) sur le serveur". Ca ne me semble pas compréhensible pour tout un chacun. Peut-être qu'une reformulation serait intéressante ici ?

2021-08-08 10:31 UTC, DanaliethPantheus commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Pour accéder aux **Analyses de Serveur**, le serveur doit soit être vérifié, soit [partenaire](https://discord.fr/wiki/programmes-communautaires/partenariat/serveur/), ou soit avoir activé la [Commun
soit être vérifié, soit **être** partenaire, **soit** avoir activé la Communauté de serveur
 --> ajout de "_être_" et suppression de "_ou_"

2021-08-08 10:31 UTC, DanaliethPantheus commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> + - La taille des serveurs suivants le serveur en question (`< 30 membres`, `30 - 200 membres`, `200 - 1000 membres`, `1000 - 10 000 membres`, `10 000 et +` et `N/A` (indéterminé).
suivant (suppression du **s**)

2021-08-08 10:31 UTC, DanaliethPantheus commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Signifiant "Ecran d'accueil", cet onglet affiche des informations sur les membres qui ont visité le serveur durant les 28 derniers jours.
C'est du chipotage, mais tant qu'à faire : **É**cran d'accueil (avec l'accent sur le E)

2021-08-08 10:31 UTC, DanaliethPantheus commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> + - Les personnes ayant vues l'écran d'accueil.
ayant **vu**

2021-08-08 14:40 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Ces dernières, particulièrement précises -notamment pour les serveurs de plus de 500 membres-, présente à travers plusieurs onglets, graphiques et chiffres l'activité du serveur et de ses membres, l'
je ne mets pas d'espaces entre les tirets et je n'ai jamais vu ça dans les livres que je lis 🤔

2021-08-08 14:41 UTC, grifgrif commented
> Hello,
> 
> Toutes les modifications demandées ont été réalisées.
> (Btw tu peux simplement m'appeler Luke)

D'accord Luke!
Petite correction orthographique et on est bon ^^

2021-08-08 14:46 UTC, LukeSkywalkerDev commented
C'est fait !

2021-08-08 14:50 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Ces dernières, particulièrement précises -notamment pour les serveurs de plus de 500 membres-, présente à travers plusieurs onglets, graphiques et chiffres l'activité du serveur et de ses membres, l'
En effet; le mot "davantage" était mal placé, maintenant ça devrait être plus compréhensible.

2021-08-08 15:46 UTC, grifgrif requested changes
Coucou Luke,

Encore une fois le lien, met quelque chose de visible!

Une fois fais je merge ^^.

2021-08-08 15:46 UTC, grifgrif commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Discord affichera un lien sur lequel il faut cliquer pour accéder à la page des statistiques. Ce lien a la forme _https://discord.com/developers/servers/identifiant-du-serveur/analytics/_.
> Discord affichera un lien sur lequel il faut cliquer pour accéder à la page des statistiques. Ce lien a la forme _https://discord.com/developers/servers/identifiant-du-serveur/analytics/_.

Visiblement tu as pas compris alors colle ca directement:

Discord affichera un lien sur lequel il faut cliquer pour accéder à la page des statistiques. Ce lien a la forme https://discord.com/developers/servers/{ID-du-serveur}/analytics/.

2021-08-08 15:54 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Discord affichera un lien sur lequel il faut cliquer pour accéder à la page des statistiques. Ce lien a la forme _https://discord.com/developers/servers/identifiant-du-serveur/analytics/_.
En effet, je n'avais pas compris ton message ainsi.

2021-08-08 15:57 UTC, LukeSkywalkerDev commented
Salut,

C'est fait ! Et btw c'est Luke, pas Alex xD

2021-08-08 15:59 UTC, grifgrif approved these changes
Enfin, tout est bon!
Je merge!

2021-08-08 15:59 UTC, merged

2021-08-08 18:13 UTC, DanaliethPantheus commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Ces dernières, particulièrement précises -notamment pour les serveurs de plus de 500 membres-, présente à travers plusieurs onglets, graphiques et chiffres l'activité du serveur et de ses membres, l'
En réalité, ce sont des espaces insécables. Word le fait automatiquement, par exemple, mais comme quasi personne ne connaît le raccourci pour les espaces insécables fines ou demi-cadratins, on met un espace avant et après les tirets d'incise. Je ne sais pas quels livres tu lis, mais les grosses maisons d'édition font particulièrement attention à la typographie (en francophonie du moins). Foi d'assistant éditorial ! ^^ 

- https://www.nouvelobs.com/abc-lettres/bien-ecrire/ponctuation.html
- https://www.la-ponctuation.com/tirets.html
- https://fr.wikipedia.org/wiki/Tiret#Tiret_moyen
- http://monsu.desiderio.free.fr/atelier/espace.html

2021-08-08 19:08 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/statistiques-serveur.md
> +Ces dernières, particulièrement précises -notamment pour les serveurs de plus de 500 membres-, présente à travers plusieurs onglets, graphiques et chiffres l'activité du serveur et de ses membres, l'
je te crois haha !
C'est vrai que quand j'écris, j'utilise Word donc je n'y fais pas attention :)