Création exigences.md
discordfr/wiki pull request #119
Opened 2021-10-27 19:49 UTC by Karal0001

**Quel est votre identifiant Discord ?**<br/> 
381574094316896258

**Décrivez rapidement vos ajouts ou changements**<br/>
J'ai créé la page, je n'ai pas fais de présentation sur ce qu'est la certification de serveur car je ne suis pas sûr que ça est sa place sur une page appelée "exigences".

2021-11-12 19:26 UTC, IchiiDev commented
Hello, du nouveau sur cette PR ?

2021-11-14 17:15 UTC, Karal0001 commented
Bonjour, Je n'ai rien d'autre à modifier, si ?

2021-11-21 11:37 UTC, IchiiDev commented
@grifgrif

2021-11-22 17:25 UTC, BenNotix requested changes

2021-11-22 17:25 UTC, BenNotix commented on programmes-communautaires/certification/exigences.md
> +- Il est nécessaire d'**associer tout compte social** de la marque/entreprise/personnalité d'intérêt publique à son profil Discord.
Préciser qu'il faut également l'associer au site lors du remplissage du formulaire sur discord.com/verification

2021-11-22 17:25 UTC, BenNotix commented on programmes-communautaires/certification/exigences.md
> +- La personne demandant la vérification doit utiliser une **adresse mail officielle** afin de montrer qu'elle occupe une fonction officielle.
Rappeler ce qu'est "une adresse mail officielle"

2021-11-22 17:25 UTC, BenNotix commented on programmes-communautaires/certification/exigences.md
> +- Original: il ne doit pas copier un autre serveur et il doit avoir son propre style, il ne peut y avoir qu'un seul serveur certifié par entreprise/marque.
Note : Discord peut faire des exceptions dans le cas où la marque possède plusieurs serveurs de régions/langues différentes.

2021-11-22 17:25 UTC, BenNotix commented on programmes-communautaires/certification/exigences.md
> +
Peut-être faire un rappel **rapide** en mettant un lien vers la page et l'article concernant la certification.

2021-11-22 21:03 UTC, Karal0001 commented on programmes-communautaires/certification/exigences.md
> +
Tu parles bien des articles et pages discord.com ?

2021-11-22 22:18 UTC, closed without merging