Create applications-autorisees.md
discordfr/wiki pull request #123
Opened 2021-11-02 11:34 UTC by PetitPotiron

**Quel est votre identifiant Discord ?**<br/> 
715826047949471785

**Décrivez rapidement vos ajouts ou changements**<br/>
Création de l'article concernant les applications OAuth2

2021-11-02 14:40 UTC, LukeSkywalkerDev requested changes
Hey,
Que penses-tu de modifier le terme "robot" par "bot", puisque c'est ce dernier qui se retrouve à la fois sur Discord et les autres articles du wiki ?

2021-11-02 14:40 UTC, LukeSkywalkerDev commented on parametres-compte/connexions-compte/applications-autorisees.md
> +Les applications sont faites pour rendre l'expérience sur Discord meilleure, mais elles peuvent toutefois être trop bien... Dans ce cas, il est possible de révoquer une application dans les paramètre
Peut-être pourrais-tu clarifier la deuxième partie de la première phrase afin de marquer davantage l'antithèse avec la première partie de cette phrase.

2021-11-05 13:25 UTC, PetitPotiron commented on parametres-compte/connexions-compte/applications-autorisees.md
> +- Lire vos informations telles que : identifiant, nom d'utilisateur, discriminateur (#0000), avatar, bannière (couleur et image), authentification à deux facteurs, souscription à [Nitro](https://disc
Note: je n'ai pas réussi à trouver de formulation qui ne s'adresse pas directement au lecteur...

2021-11-05 13:25 UTC, PetitPotiron commented on parametres-compte/connexions-compte/applications-autorisees.md
> +:::note Une application ne pourra jamais lire ou envoyer de messages à votre place. :::
Note: je n'ai pas réussi à trouver de formulation qui ne s'adresse pas directement au lecteur...

2021-11-05 15:26 UTC, LukeSkywalkerDev commented on parametres-compte/connexions-compte/applications-autorisees.md
> +- Lire vos informations telles que : identifiant, nom d'utilisateur, discriminateur (#0000), avatar, bannière (couleur et image), authentification à deux facteurs, souscription à [Nitro](https://disc
Salut,
Voici quelques exemples pour t'aiguiller : 

> - Créer des Slash commands sur votre serveur.
- Créer des slash commands sur un serveur.

> - Lire **vos** informations
- Lire les informations  des utilisateurs ayant autorisé l'application a accéder à celles-ci.

2021-11-05 15:31 UTC, LukeSkywalkerDev requested changes

2021-11-05 15:31 UTC, LukeSkywalkerDev commented on parametres-compte/connexions-compte/applications-autorisees.md
> +Les applications peuvent nécessiter plusieurs permissions, voici les plus communes :
Modifier le verbe "nécessiter" par "demander l'accès à" peut-être ici plus adéquat.

2021-11-06 17:52 UTC, BenNotix approved these changes

2021-11-06 17:53 UTC, merged