Update roles.md
discordfr/wiki pull request #124
Opened 2021-11-04 18:24 UTC by Feoxy

Ajout de la nouvelle fonctionnalité "Badges de rôles".

**Quel est votre identifiant Discord ?**<br/> 
707559278348730479

**Décrivez rapidement vos ajouts ou changements**<br/>
J'ai rajouté la nouvelle fonctionnalité de discord, la possibilité d'ajouter des **badges / icônes** de rôles.

Explication, Comment Ajouter un Badge et ce que ca donne à la fin sur le profil et la liste de membres

2021-11-04 18:42 UTC, PetitPotiron requested changes
Bonsoir très bonne idée, il reste néanmoins une chose à changer pour moi.

2021-11-04 18:42 UTC, PetitPotiron commented on configuration-serveur/configuration-serveur/roles.md
> +Le badge de rôle permet de rajouter une icône à côté de votre pseudo dans la liste des membres, ainsi que sur votre profil.
Ne pas s'adresser au lecteur directement : "votre", "vous" sont à proscrire.

2021-11-04 19:18 UTC, Feoxy commented on configuration-serveur/configuration-serveur/roles.md
> +Le badge de rôle permet de rajouter une icône à côté de votre pseudo dans la liste des membres, ainsi que sur votre profil.
> Ne pas s'adresser au lecteur directement : "votre", "vous" sont à proscrire.

Je suis en effet d'accord avec vous, je vais modifier cela !

2021-11-04 20:37 UTC, Feoxy commented
Je viens d'effectuer le changement

2021-11-05 20:09 UTC, grifgrif requested changes
Bonjour,

Votre article connait un bon début mais néanmoins possède quelques lacunes.

L'utilisation du vous et à proscrire, préférez d'autres moyens de le dire.
La structure en liste est confuse, un paragraphe explicatif ferai mieux l'affaire. Essayez de faire des catégories puis des paragraphes et pas des listes dans des catégories.
Vous devez vous détacher du tutoriel et passer sur un mode plus Wiki. Pas "d'étape par étape" mais plus du "L'option des paramètres de rôles peut se trouver dans les permissions".
Vous pouvez demander aux contributeur de vous fournir des images professionnelles pour accompagner vos articles, en effet ils ont accès à un salon avec les graphistes de discord.fr.

Sinon c'est pas mal.

Je vous remercie de votre bon début d'article et je serai ravi de lire ce dernier corrigé.

A bientôt,
GrifGrif.

2021-11-05 20:09 UTC, grifgrif commented on configuration-serveur/configuration-serveur/roles.md
> +#### Pour cela il vous suffit de se rendre dans les paramètres de rôles, de choisir un rôle et de cliquer ici:
Trop Tutoriel.

2021-11-05 20:09 UTC, grifgrif commented on configuration-serveur/configuration-serveur/roles.md
> +###### À noter que vous devez avoir le level 2 de boost sur votre serveur pour pouvoir mettre les badges.
"Vous" a proscrire.

2021-11-05 20:09 UTC, grifgrif commented on configuration-serveur/configuration-serveur/roles.md
> +Le badge de rôle vous permet de rajouter une icône à côté de votre pseudo dans la liste de vos membres, ainsi que sur votre profil.
"Votre" à proscrire.

2021-11-05 22:47 UTC, Feoxy commented
Bonsoir GrifGrif,

Il n'y a pas de problème, je comprends très bien ce que je vais faire est que je vais le modifier et je vais voir avec les contributeurs du serveur.

Bonne Soirée

2021-11-06 13:46 UTC, Feoxy commented
Je viens d'effectuer une modification, j'ai refais tout le texte et ajouté les images "i.discord.fr"

2021-11-13 16:45 UTC, grifgrif approved these changes
Bonjour,

Tout est bon de mon côté. Merci de ta participation ^^

J'approuve tout de suite :D

2021-11-13 16:45 UTC, merged