Mistakes
discordfr/wiki pull request #130
Opened 2021-11-08 18:46 UTC by PetitPotiron

**Quel est votre identifiant Discord ?**<br/> 
715826047949471785

**Décrivez rapidement vos ajouts ou changements**<br/>
Correction de plusieurs erreurs :)

2021-11-09 06:15 UTC, IchiiDev commented
Merci de me confirmer une fois que la PR sera complète. Vous avez actuellement créé un draft.

2021-11-12 19:30 UTC, IchiiDev requested changes
Juste une chose à corriger

2021-11-12 19:30 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/badges.md
> +:::note Plus d'informations sur les boosts sont lisibles [ici](https://discord.fr/wiki/nitro-jeux/boost-serveur/boost/):::
Je dirais plutôt "accéssibles" plus que lisibles

2021-11-13 08:37 UTC, PetitPotiron commented on programmes-communautaires/outils-communautaires/badges.md
> +:::note Plus d'informations sur les boosts sont lisibles [ici](https://discord.fr/wiki/nitro-jeux/boost-serveur/boost/):::
Oui c'est vrai que c'est plus clair 👀

2021-11-13 16:36 UTC, IchiiDev approved these changes
LGTM

2021-11-13 16:36 UTC, closed without merging