Update badges.md
discordfr/wiki pull request #133
Opened 2021-11-14 13:42 UTC by Fizle

**Quel est votre identifiant Discord ?**<br/> 
Entrez votre ID ici : 596108145592500276

**Décrivez rapidement vos ajouts ou changements**<br/>
Ajout badge HypeSquad en or

2021-11-17 19:17 UTC, LukeSkywalkerDev requested changes
Hello,

C'est une modification intéressante, n'oublie simplement pas de garder le style informatif ainsi que d'ajouter un nom pour chaque image que tu fournis entre les crochets :p

2021-11-17 19:17 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +⚠️  Attention à ne pas confondre avec le badge attribué aux membres participant à l'Hypesquad et qui assistent à des conventions (HypeSquad Évent Coordinators) ou qui organisent des évènements comme
Vous pouvez utiliser le format suivant pour mettre l'emphase sur un élément important :

:::warning 
Message
:::

2021-11-17 19:17 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +je parle évidemment du badge *[EventHypesquad]* (https://discord.fr/wiki/programmes-communautaires/hypesquad/hypesquad-events/)). (https://user-images.githubusercontent.com/93324402/141604020-76fa86c
Il faudrait éviter d'usiter des pronoms personnels inclusifs ("je", "nous") au profit de pronoms personnels plus neutres ("il",...)

2021-11-17 19:17 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +Comme nous le savons il existe trois badges différenciés de la Hypesquad, que l’on appelle autrement : House of  Bravery, House of Brillance et enfin, House of Balance *(tous y sont référenciés dans
"Nous" ne le savons pa forcément, il conviendrait peut-être de retirer cette partie de la phrase pour ne pas faire culpabiliser les personnes ignorantes sur ce sujet. Tu peux sinon utiliser un groupe nominal de rappel, tel que "Comme évoqué antérieurement,...).

2021-11-17 19:17 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +    ##**Comment obtenir le badge ? Quel est son utilité ?**
*Quelle

2021-11-17 19:17 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +Toutefois seule une maison à la fois ne pouvait détenir le badge. Une maison a « gagné », c’est celle qui a donné le plus d’argent à l’organisme de bienfaisance
Peut-être serait-il intéressant de remplacer "qui a donné le plus d'argent" par "dont les membres ont réalisé la plus grande donation"

2021-11-17 19:17 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +*(c’était la House of Balance :p)*. Enfin les membres étant sur discord à ce moment-là ont reçu des mails pour l’annonce de cet évènement, ils sont aujourd’hui très rares et uniques. C’est à se deman
La phrase "c'est à se demander s'ils ne sont pas historiques" est-elle réellement pertinente, étant donné qu'il s'agit d'une forme de parti-pris ? Je serais plutôt d'avis à l'enlever.

2021-11-17 19:17 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +**Aujourd’hui les badges ne sont plus disponibles.**
Rappelle que tu parles bien ici des badges "en or" et non pas des badges hso en général

2021-11-17 21:56 UTC, Fizle commented
Fait ! 
Merci ;) 👍

2021-11-18 06:50 UTC, LukeSkywalkerDev requested changes
Hello,

Encore quelques petites choses, et je pense que ce sera bon :) Donc, il reste encore à modifier l'image, le titre ainsi que la signalisation de l'avertissement en utilisant les balises docusaurus (```
:::warning 
texte
":::```)

Au niveau des liens n'oublie pas que tu ne dois pas mettre d'espace entre les crochets et les parenthèses (ex : `[url](https://url.com)`) ; et si tu souhaites utiliser un moyen emphatique, telle que gras, il faut le placer avant le premier crochet et après la dernière parenthèse (ex : `**[url](https://url.com)**`). Si tu ne respectes pas ces conditions, le md ne forme pas de lien hypertexte.

2021-11-18 06:50 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +    #**Badge de la Hypesquad en or :**
Tu n'as pas besoin de mettre un titre en gras, tu peux aussi mettre un titre de niveau 3 ici, puisqu'il s'agit d'une sous partie sur les badges hso. Et n'oublie pas de mettre un espace entre les `###` et le nom du titre :)

2021-11-18 18:22 UTC, LukeSkywalkerDev requested changes
Il ne reste plus qu'à modifier les liens des images et les hypertextes afin que le lien fonctionne correctement ! On y est presque :)

2021-11-18 18:22 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +[Badge en or HS profil](https://user-images.githubusercontent.com/93324402/142389952-6578ebd5-dc4d-4d8f-ae55-b124378a9099.JPEG)
Tu peux remplacer le lien par https://i.discord.fr/BMxk.jpg

2021-11-18 18:22 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/badges.md
> +[Badge_en_or_Hypesquad_2](https://user-images.githubusercontent.com/93324402/142391034-9ad7cdda-5d8c-4dc2-a4a1-0e8d87999851.png)
Tu peux remplacer ce lien par : https://i.discord.fr/LtdH.png

2021-11-19 06:49 UTC, LukeSkywalkerDev commented
Tout me semble bon !

2021-11-21 17:18 UTC, Fizle commented
Tout est bon je crois bien ;)

2021-11-22 13:21 UTC, BenNotix approved these changes
Modifications intéressantes et pertinentes. Plus de fautes à corriger, au vu des corrections apportées par @LukeSkywalkerDev

2021-11-22 13:22 UTC, merged