Update evenements.md
discordfr/wiki pull request #134
Opened 2021-11-21 10:46 UTC by LukeSkywalkerDev

Hello,

J'ai rédigé l'article sur les évènements en utilisant https://support.discord.com/hc/en-us/articles/4409494125719-Scheduled-Events et mes connaissances comme sources.
 
Bonne relecture :p

**Quel est votre identifiant Discord ?**<br/> 
585166080071172098

**Décrivez rapidement vos ajouts ou changements**<br/>
Rédaction de l'article sur les évènements de serveur.

2021-11-21 11:40 UTC, PetitPotiron requested changes
Hey, à première vue, ça m'a l'air d'être un très bon article 👀!

2021-11-21 11:40 UTC, PetitPotiron commented on programmes-communautaires/outils-communautaires/evenements.md
> +Les **Scheduled Events**, littéralement "évènements programmés", ont pour objectif d'afficher les évènements en cours/prévus afin de permettre à la communauté du serveur d'accéder facilement aux info
"la communauté du serveur" -> je pense qu'il serait mieux de ne pas parler d'un serveur en particulier, et de privilégier "d'un serveur". J'effectuerais le même changement pour "de l'évènement." du coup ^^.

2021-11-21 11:40 UTC, PetitPotiron commented on programmes-communautaires/outils-communautaires/evenements.md
> +En cliquant sur la case `Evènements` située en haut des salons du serveur, il est possible de visualiser les différents évènement programmés. En cliquant sur un évènement en particulier, la plateform
- Pour moi, la case événements commence par un é majuscule... Si tu ne sais pas comment l'écrire, le voici : `É` (Alt+144 sur windows)
- "les différents évènement programmés" il y a plusieurs évènements, il serait donc bien de rajouter un -s à `évènement`

2021-11-21 12:14 UTC, LukeSkywalkerDev commented
C'est corrigé !

2021-11-21 12:18 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +En cliquant sur la case `Evènements` située en haut des salons du serveur, il est possible de visualiser les différents évènement programmés. En cliquant sur un évènement en particulier, la plateform
Je connais le raccourci mais je n'arrive jamais à le faire xD 
My bad pour la faute d'orthgraphe ^^

2021-11-21 12:50 UTC, PetitPotiron commented
> Salut, c'est corrigé ! Merci du review ;)
Ça m'a l'air juste super, à priori il n'y a plus qu'à merge 👀

2021-11-23 19:37 UTC, IchiiDev requested changes
Encore des choses à revoir, merci de rester informatif plutot que didactique dans la rédaction de vos articles.

2021-11-23 19:37 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +Discord propose d'organiser un évènement directement sur l'application (soit dans un salon vocal, soit dans un [Stage Channel](https://discord.fr/wiki/interface/salon-vocal/stage-channels/)), ou alor
Il serait préférable de changer en "Il est possible d'organiser...".
La deuxième phrase est lourde + ouvre sur un tutoriel (ce qui n'est pas ce que l'on cherche)

2021-11-23 19:37 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +Une fois un évènement créé, il est possible d'éditer les informations sur l'évènement ou de l'annuler. Pour ce faire, il faut appuyer sur les points de suspension situés sous l'évènement en question.
La deuxième phrase n'est pas pertinente et peut être remplacée par "[...] ou de l'annuler en cliquant sur les points de suspention sous l'évènement."

2021-11-23 19:37 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +Lorsque l'évènement débute, il faut cliquer sur "Commencer l'évènement" et sur "Terminer l'évènement" une fois ce dernier fini.
Petit point trivia, il n'est pas nécéssaire de débuter ou de stopper manuellement un article si un horaire de début et de fin est défini. Discord s'en chargera automatiquement (hormis évènements stage qui s'arrêteront quand tout les speakers auront quitté le stage)

2021-11-24 06:05 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +Discord propose d'organiser un évènement directement sur l'application (soit dans un salon vocal, soit dans un [Stage Channel](https://discord.fr/wiki/interface/salon-vocal/stage-channels/)), ou alor
Pas de problème pour la formulation de la phrase d'annonce, par contre au niveau de la description par points, tu souhaiterais que je la remplace en un résumé de la façon de débuter un évent, c'est bien ça ?

2021-11-28 09:33 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +Discord propose d'organiser un évènement directement sur l'application (soit dans un salon vocal, soit dans un [Stage Channel](https://discord.fr/wiki/interface/salon-vocal/stage-channels/)), ou alor
C'est ça, mais en précisant où se trouvent les paramètres plutôt que d'expliquer pas à pas la marche à suivre.

2021-11-28 13:06 UTC, LukeSkywalkerDev commented
Les modifications demandées ont été effectuées.

2021-12-01 12:55 UTC, IchiiDev requested changes
Encore des choses à revoir

2021-12-01 12:55 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +En cliquant sur la case `Évènements` située en haut des salons du serveur, il est possible de visualiser les différents évènements programmés. En cliquant sur un évènement en particulier, la platefor
"[...] s'étant déclarées "Intéress**ées**" par l'évènement"

2021-12-01 12:55 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +Afin de partager un évènement, il est nécessaire de disposer de la permission `Créer une invitation`. Il faut ensuite se rendre sur le bouton "Évènements" et cliquer sur "Partager".
La répétition de la formulation "afin" fait lourd

2021-12-01 12:55 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +Plusieurs informations sont ensuite demandées par l'application dans le menu qui s'ouvre, à savoir l'emplacement de l'évènement (soit dans un salon vocal, soit dans un [Stage Channel](https://discord
La dernière phrase rend compte d'un tutoriel, pouvez vous la reformuler ?

2021-12-01 12:55 UTC, IchiiDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +Discord propose la planification d'évèneemnts directement sur l'application. Il est possible d'en organiser un en sélectionnant l'option "Créer un évènement", situé dans la barre de menu en-dessous d
Vous avez fait une faute à évènements

2021-12-01 18:27 UTC, LukeSkywalkerDev commented on programmes-communautaires/outils-communautaires/evenements.md
> +En cliquant sur la case `Évènements` située en haut des salons du serveur, il est possible de visualiser les différents évènements programmés. En cliquant sur un évènement en particulier, la platefor
Il s'agit d'une citation de l'onglet en question, je l'ai néanmoins modifié

2021-12-01 18:53 UTC, LukeSkywalkerDev commented
Modifications réalisées

2021-12-02 20:17 UTC, IchiiDev approved these changes
LGTM

2021-12-02 20:18 UTC, merged