Update modeles.md
discordfr/wiki pull request #137
Opened 2021-12-01 11:05 UTC by PetitPotiron

**Quel est votre identifiant Discord ?**<br/> 
715826047949471785

**Décrivez rapidement vos ajouts ou changements**<br/>
Création de l'article sur les modèles de serveurs (je l'avais déjà créé sur un double-compte, et comme la PR #115 est fermée, je poste mes modifications)

2021-12-03 19:41 UTC, IchiiDev requested changes
Beaucoup de choses à revoir. Je vous conseille d'ouvrir d'autres articles avant d'ouvrir une pull request.

2021-12-03 19:41 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/modeles.md
> +Un serveur Discord peut à tout moment devenir un **modèle de serveur**. Il permet de faire une copie de la configuration du serveur facilement et d'aider quelqu'un d'autre à créer un serveur instanta
Le serveur ne change pas d'état, il est juste possible de prendre une capture de l'état du serveur (Roles, Salons, Permissions)

2021-12-03 19:41 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/modeles.md
> +:::caution Attention ! Les modèles de serveur ne copient pas les messages, threads ou tout autre contenu, les membres ou bots ainsi que l'icône du serveur, ses [boosts](https://discord.fr/wiki/nitro-
Faites attention à bien séparer les lignes pour les bulles d'informations:
```
:::caution Attention !
Texte
:::
```

2021-12-03 19:41 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/modeles.md
> +### Création
Utilisez des titres de niveau 2 en priorité

2021-12-03 19:41 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/modeles.md
> +Pour créer un modèle de serveur, il faut se rendre dans `Paramètres du serveur > Modèle de serveur`. À cet endroit se trouve un formulaire pour décrire le serveur en question, et, une fois validé, un
Attention à ne pas faire de tutoriel ! ⚠️

2021-12-15 13:54 UTC, LukeSkywalkerDev commented
Hey, peut-être serait-il intéressant de "cacher" le lien du modèle discord.new présent sur l'image afin de ne pas le rendre accessible/viisble aux lecteurs.

2021-12-15 17:15 UTC, PetitPotiron commented
> Hey, peut-être serait-il intéressant de "cacher" le lien du modèle discord.new présent sur l'image afin de ne pas le rendre accessible/viisble aux lecteurs.

En l'occurence j'ai supprimé le modèle après la création de l'article mais c'est vrai que je ne sais pas s'il serait judicieux de modifier le lien présent vers un lien `discord.new/xxxxxxxx`... J'attends pour ça l'avis des reviewers mais je prends note!

2021-12-16 14:01 UTC, IchiiDev requested changes
Encore des choses à revoir. 
Concernant l'idée de cacher le lien dans l'image: Si jamais le lien est invalide, pas besoin de le censurer

2021-12-16 18:24 UTC, PetitPotiron commented on configuration-serveur/configuration-serveur/modeles.md
> +:::
C'est vrai que je n'y ai pas porté attention, j'ai juste supprimé une bonne partie de l'article sans relire les bulles d'informations 😅. Le problème est corrigé.

2021-12-17 18:12 UTC, IchiiDev approved these changes
LGTM

2021-12-17 18:12 UTC, merged