Update mode-developpeur.md
discordfr/wiki pull request #138
Opened 2021-12-05 16:16 UTC by MaxenceGu21

Page complétée : Explication du mode développeur sur Discord.

**Quel est votre identifiant Discord ?**<br/> 
864423158806347796

**Décrivez rapidement vos ajouts ou changements**<br/>
- Explication du fonctionnement du mode développeur sur Discord.

2021-12-05 16:44 UTC, LukeSkywalkerDev requested changes
Salut,

C'est un bon début d'article, peut-être serait-il intéressant d'illustrer par ailleurs l'article avec des captures d'écran de l'endroit où est situé ce bouton, qu'en penses-tu ?

2021-12-05 16:44 UTC, LukeSkywalkerDev commented on interface/fonctionnalites/mode-developpeur.md
> +# A quoi sert le mode développeur sur Discord ?
N'hésite pas à mettre un titre de niveau 2 (`##`) puisque le titre de niveau 1 est automatiquement utilisé pour le nom de l'article et à laisser une ligne entre le titre de la section et le paragraphe explicatif.

2021-12-05 16:44 UTC, LukeSkywalkerDev commented on interface/fonctionnalites/mode-developpeur.md
> +Le mode développeur permet d'activer des options supplémentaires sur Discord. L'intérêt principal à activer le mode développeur est de pouvoir récupérer l'identifiant (ID) d'un utilisateur, d'un mess
Il faudrait éviter d'utiliser une tournure indicative au profit d'une tournure informative ("lorsque vous faites"). Par ailleurs, je pense qu'il peut être préférable d'utiliser "..." pour les points de suspension de l'énumération au lieu de 4 points, puisqu'il s'agit de la norme actuelle. À défaut, peut-être choisir dans l'article soit l'utilisation de la ponctuation soit une expression latine (_et caetera_) qui serait usité tout du long afin d'éviter une disparité d'expression d'une énumération.

2021-12-05 20:17 UTC, MaxenceGu21 commented
> Salut,
> 
> C'est un bon début d'article, peut-être serait-il intéressant d'illustrer par ailleurs l'article avec des captures d'écran de l'endroit où est situé ce bouton, qu'en penses-tu ?

Je ne pense pas que cela soit une bonne idée car j'ai peur que le tutoriel prenne une tournure de tutoriel !

2021-12-05 20:18 UTC, MaxenceGu21 commented on interface/fonctionnalites/mode-developpeur.md
> +# A quoi sert le mode développeur sur Discord ?
✅

2021-12-05 20:18 UTC, MaxenceGu21 commented on interface/fonctionnalites/mode-developpeur.md
> +Le mode développeur permet d'activer des options supplémentaires sur Discord. L'intérêt principal à activer le mode développeur est de pouvoir récupérer l'identifiant (ID) d'un utilisateur, d'un mess
✅

2021-12-06 05:51 UTC, LukeSkywalkerDev commented
Tu m'as certainement mal compris, j'ai proposé l'ajout d'une capture d'écran présentant l'endroit où il est possible de récupérer l'identifiant (en effectuant un clique-droit), 


_Btw ce n'est pas un tutoriel, mais un article_

2021-12-06 06:24 UTC, MaxenceGu21 commented
> Tu m'as certainement mal compris, j'ai proposé l'ajout d'une capture d'écran présentant l'endroit où il est possible de récupérer l'identifiant (en effectuant un clique-droit),
> 
> _Btw ce n'est pas un tutoriel, mais un article_

C'est bon, j'ai essayé de faire un petit truc avec l'image, peux-tu me dire ce que tu en penses s'il te plaît ?

2021-12-06 17:16 UTC, IchiiDev requested changes

2021-12-06 17:41 UTC, MaxenceGu21 commented on interface/fonctionnalites/mode-developpeur.md
>  Vous voulez contribuer à cette page ? Faites une pull request sur [notre repository GitHub](https://github.com/discordfr/wiki). Suivez les instructions sur [notre page dédiée](https://discord.fr/wiki
✅

2021-12-06 20:21 UTC, LukeSkywalkerDev commented
> C'est bon, j'ai essayé de faire un petit truc avec l'image, peux-tu me dire ce que tu en penses s'il te plaît ?

Il pourrait aussi être intéressant de rajouter une image de l'endroit où l'on peut activer le mode développeur, et ça devrait être bon pour moi ^^

2021-12-09 19:42 UTC, IchiiDev commented
> > C'est bon, j'ai essayé de faire un petit truc avec l'image, peux-tu me dire ce que tu en penses s'il te plaît ?
> 
> Il pourrait aussi être intéressant de rajouter une image de l'endroit où l'on peut activer le mode développeur, et ça devrait être bon pour moi ^^

Je valide cette suggestion, en attente d'un ajout / proposition par un contributeur

2021-12-10 16:59 UTC, IchiiDev approved these changes
LGTM !

2021-12-10 16:59 UTC, merged