Update dossiers-de-serveurs.md
discordfr/wiki pull request #150
Opened 2022-01-09 11:09 UTC by PetitPotiron

The article was directly speaking to the reader.

**Quel est votre identifiant Discord ?**<br/> 
715826047949471785

**Décrivez rapidement vos ajouts ou changements**<br/>
Une phrase s'adressait directement au lecteur, ce qui est contraire au style de rédaction du wiki.

2022-01-17 20:01 UTC, grifgrif requested changes
Bonjour,

Il me semble que vous supprimez trop de contenu/ les titres dans le document "Dossiers-de-serveurs.md".
Dès que l'article est bon je n'ai rien à dire sur le reste.

2022-01-17 21:07 UTC, PetitPotiron commented
> Bonjour,
> 
> Il me semble que vous supprimez trop de contenu/ les titres dans le document "Dossiers-de-serveurs.md". Dès que l'article est bon je n'ai rien à dire sur le reste.

Bonjour,

Je n'ai pas compris ce qui pose problème, je n'ai pas changé de titre dans le document `Dossiers-de-serveurs.md`, j'ai seulement fait en sorte que l'article ne parle pas directement au lecteur...

2022-01-22 13:54 UTC, IchiiDev commented
Pull request réattribuée suite à l'inactivité de @grifgrif pendant plus de 4j

2022-01-23 13:21 UTC, IchiiDev requested changes
Quelques choses à revoir, j'ai expliqué ce que GrifGrif avait pointé la dernière fois.

2022-01-23 13:21 UTC, IchiiDev commented on interface/fonctionnalites/dossiers-de-serveurs.md
> -![Personnalisation d'un dossier](https://i.discord.fr/bvC.png)
Ces lignes peuvent être reformulées au lieu d'être simplement supprimées

2022-01-23 13:21 UTC, IchiiDev commented on interface/fonctionnalites/dossiers-de-serveurs.md
> +Pour créer un dossier de serveurs, il faut maintenir un serveur et le faire glisser sur un autre. Il en va de même pour l'ajout d'un serveur dans un dossier. Un clic droit sur le dossier et sur "Para
La formulation reste maladroite et proche d'un tutoriel. Je précognise l'ouverture suivante: "La création d'un dossier de serveur s'effectue via..."

2022-01-23 13:21 UTC, IchiiDev commented on interface/fonctionnalites/dossiers-de-serveurs.md
> +Les dossiers de serveurs permettent de trier les serveurs, de les séparer afin d'avoir une meilleure expérience utilisateur. La personnalisation de la couleur, du nom du dossier y est possible. Les b
La dernière phrase est floue, reformulez le terme "badge de mention"

2022-01-23 18:33 UTC, PetitPotiron reviewed
Je crois avoir fait le nécessaire 👍

2022-01-23 19:22 UTC, IchiiDev requested changes

2022-01-23 19:22 UTC, IchiiDev commented on interface/fonctionnalites/dossiers-de-serveurs.md
>  ### Que sont les dossiers de serveurs ?
Il n'est pas conseillé de commencer par un titre

2022-01-26 09:09 UTC, IchiiDev reviewed
Encore une fois, un titre n'est pas pertinent pour entamer un article, il serait judicieux de le retirer sur tous les articles modifiés. Ca fera partie des différentes modifications à faire sur le restant des articles.

2022-01-29 09:38 UTC, IchiiDev approved these changes
LGTM

2022-01-29 09:39 UTC, merged