Update widget.md
discordfr/wiki pull request #153
Opened 2022-01-14 21:45 UTC by Karal0001

**Quel est votre identifiant Discord ?**<br/> 
Entrez votre ID ici

**Décrivez rapidement vos ajouts ou changements**<br/>
Création de la page

2022-01-15 06:50 UTC, LukeSkywalkerDev requested changes
Salut,

C'est un bon début, il y a néanmoins encore plusieurs choses à revoir ;)

2022-01-15 06:50 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/widget.md
> +Un widget c'est l'aperçu d'un serveur Discord directement sur une page internet.
Dans un souci de clarté, il serait peut-être intéressant de retirer le "c'est" qui tient davantage du langage oral que de l'écrit, ce qui donnerait ainsi "un widget __permet__ l'affichage de l'aperçu d'un serveur Discord [...]"

2022-01-15 06:50 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/widget.md
> +![aperçu widget](https://i.imgur.com/cTOQqXw.png)
Tu peux remplacer le lien par celui-ci : https://i.discord.fr/JtbZ.png

2022-01-15 06:50 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/widget.md
> +Après s'être rendu dans la section "Widget" du serveur (cadre rouge) il faut activer l'activer (vert). Enfin, il faut copier-coller la balise HTML contenant le widget (orange).
Il faudrait peut-être préciser que la section "Widget" se situe dans les paramètres du serveur et remplacer le deuxième "faut" par un synonyme.

2022-01-15 06:50 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/widget.md
> +![Section widget](https://i.imgur.com/790VGVT.png)
Tu peux éditer le lien par https://i.discord.fr/LmPt.png

2022-01-15 06:50 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/widget.md
> +Le widget copié possède des paramètres par defaut tels que la hauteur, la largeur et le thème qui peuvent être modifiés.
Peut-être faudrait-il bien préciser qu'il s'agit de la balise HTML du widget qui dispose de ces "paramètres"

2022-01-15 10:00 UTC, PetitPotiron commented on configuration-serveur/configuration-serveur/widget.md
> +Après s'être rendu dans la section "Widget" du serveur (cadre rouge) il faut activer l'activer (vert). Enfin, il faut copier-coller la balise HTML contenant le widget (orange).
Il serait peut-être intéressant d'expliquer que cette balise HTML est uniquement destinée aux développeurs du site internet.

2022-01-15 10:30 UTC, Karal0001 commented
Merci pour vos relectures

2022-01-21 08:55 UTC, IchiiDev requested changes
Quelques choses à revoir

2022-01-21 08:55 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/widget.md
> +:::
Cette partie ressemble trop à un tutoriel. Une approche plus correcte serait "Le widget s'active dans..." puis "la balise s'intègre dans n'importe quelle page web..."

2022-01-21 08:55 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/widget.md
> +Un widget permet l'aperçu d'un serveur Discord directement sur une page internet.
L'introduction pourrait définir les informations que l'on peut retrouver dans un widget

2022-01-21 08:55 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/widget.md
> +## Qu'est-ce qu'un widget ?
Il est déconseillé de commencer un article par un sous titre

2022-01-25 06:55 UTC, Karal0001 commented
Bonjour,
Je m'occupe de faire les modifications demandées ce week-end.

2022-01-29 12:12 UTC, Karal0001 reviewed
Je viens d'apportter les modifications demandées

2022-01-29 13:40 UTC, IchiiDev requested changes

2022-01-29 13:40 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/widget.md
> +### Qu'est-ce qu'un widget ?
Encore une fois, il est déconseillé de commencer un article par un titre car un titre de niveau 1 est déjà généré par le site sur chaque article

2022-01-29 13:40 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/widget.md
> +### Comment utiliser un widget ?
Merci de respecter la hierarchie des titres et commencer par des titres de niveau 2

2022-01-29 14:04 UTC, Karal0001 commented
Normalement tous est corrigé ^^

2022-01-29 17:33 UTC, IchiiDev requested changes

2022-01-29 17:33 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/widget.md
> +Un widget permet d'avoir un aperçu d'un serveur Discord directement sur une page internet. On peut y trouver divers informations sur le serveur: son nombre et sa liste de membres, ses salons, sa phot
"Sa photo de profil" -> "icone"

2022-01-30 15:48 UTC, PetitPotiron commented on configuration-serveur/configuration-serveur/widget.md
> +Un widget permet d'avoir un aperçu d'un serveur Discord directement sur une page internet. On peut y trouver divers informations sur le serveur: son nombre et sa liste de membres, ses salons, sa phot
"divers" -> "divers**e**"

2022-02-02 15:22 UTC, IchiiDev approved these changes
LGTM

2022-02-02 15:22 UTC, merged