MAJ a2f
discordfr/wiki pull request #176
Opened 2022-07-26 08:00 UTC by volcanofr

- Correction de fautes d'orthographe
 - Reformulation d'une phrase

2022-07-26 16:52 UTC, IchiiDev requested changes
Quelques choses à revoir. Pensez bien à la pertinence de vos changements au moment de les effectuer !

2022-07-26 16:52 UTC, IchiiDev commented on parametres-compte/connexion-verification/a2f.md
> +La fonctionnalité de [QR Code](https://discord.fr/wiki/parametres-compte/connexion-verification/qr-code.md) passera toujours outre l'authentification à deux facteurs.
Le changement de la bulle d'information de `note` à `info` n'est pas pertinent.

2022-07-26 16:52 UTC, IchiiDev commented on parametres-compte/connexion-verification/a2f.md
> +Lors de l'activation de l'A2F, Discord génère des codes de secours générés aléatoirement. Dans le cas où l' utilisateur perd son application d'authentification, il sera alors possible d'utiliser un d
Le changement de cette ligne n'est pas pertinent, le sens est flou et répétitif (deux fois "génère" ou similaire dans la même phrase). L'idée principale est déjà présente et claire dans la version originale, pas besoin de cette reformulation.

2022-07-27 15:09 UTC, volcanofr commented
> * Correction de fautes d'orthographe
> * Reformulation d'une phrase

2022-07-27 15:09 UTC, closed without merging