Update /configuration-serveur/
discordfr/wiki pull request #178
Opened 2022-07-28 14:35 UTC by volcanofr

**Quel est votre identifiant Discord ?**<br/> 
589383722759880705

**Décrivez rapidement vos ajouts ou changements**<br/>
__Mise à Jour des pages du wiki, catégorie `configuration-serveur/` :__
- Correction de fautes d'orthographes et de grammaire ;
- Ajout d'informations ;
- Ajout de liens ;
- Réglage de problèmes visible uniquement sur https://discord.fr/wiki/ ;
- Et quelques autres choses...

2022-07-29 16:36 UTC, volcanofr commented
Je serai en vacances ce WE et toute la semaine qui arrive, je serai donc indisponible pendant ce temps.

2022-08-02 12:51 UTC, volcanofr commented
Je regarde quand même de temps en temps 👀

2022-08-27 05:54 UTC, LukeSkywalkerDev requested changes
Hello,

Merci beaucoup pour tes diverses propositions pertinentes !
Tu as déjà fait un grand travail, cependant, je t'ai mis mes suggestions de modification - il y a quelques étourderies, à l'instar de fautes d'orthographes ou d'imprécisions.

Bonne journée ! :)

2022-08-27 05:54 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/gestion-emojis-et-stickers.md
> +La gestion des émojis personnalisés se fait dans la catégorie `Émoji` des paramètres du serveur. Il est alors possible d'ajouter des images fixe pu animés, dont la taille est inférieure à 256 Ko (ou
Tu as fait une faute ici :  "Il est alors possible d'ajouter des images fixe pu animés" -> "Il est alors possible d'ajouter des images fixe**s** ~~p~~**o**u animé**e**s"

2022-08-27 05:54 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/gestion-emojis-et-stickers.md
> +Pour ajouter une image en tant qu'émoticone, il suffit de suivre le chemin précédemment énoncé et cliquer sur "Uploader un émoji". Il est possible d'ajouter des émojis animés sous format GIF, ainsi q
Peut-être serait-il plus judicieux de remplacer ici le terme "chemin" par "procédure" ou un synonyme ;)

2022-08-27 05:54 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/gestion-emojis-et-stickers.md
> +Il est possible de modifier le nom d'un émoji, en cliquant entre les deux-points et en écrivant le que l'on souhaite. Le nom des émojis est constitué de 2 charactères autorisés minimum (lettres majuc
Le terme "charactères" s'écrit sans "h", tu as peut-être confondu avec le mot anglais "character" (personnage) x)

2022-08-27 05:54 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/gestion-emojis-et-stickers.md
> +Pour supprimer un émoji, il faut simplement aller dans la section `Émoji` des paramètres du serveur, et en survolant la ligne conrrespondant à l'émoji que l'utilisateur souhaite enlever, un croix rou
Tu as oublié le "e" féminin à "une croix rouge". 
Sinon, à titre de suggestion - c'est à toi de voir, peut-être pourrait-on éditer "aller" par "se rendre", qui est légèrement moins passe-partout que le premier verbe

2022-08-27 05:54 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/roles.md
> +Les permissions des salons sont prioritaires quand elles sont vertes. (voir article des [permissions générales](https://discord.fr/wiki/configuration-serveur/permissions/generales/))
Peut-être serait-il intéressant de modifier "voir article" par "cf article", il s'agit ici aussi d'une suggestion

2022-08-27 05:54 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/roles.md
> +Il n'est pas possible de configurer le nom, l'icône et la couleur de celui-ci, tout comme il est impossible de supprimer ou encore de se retirer ce rôle - il est invisible mais bien présent chez tout
Je pense qu'il faudrait préciser "tout le monde" -> "tous les utilisateurs"

2022-08-27 05:54 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/roles.md
> +:::caution À noté
Tu as fait une faute ici : "à noté" -> "à noter" _ou encore, Nota bene (N. B.)_

2022-08-27 05:54 UTC, LukeSkywalkerDev commented on configuration-serveur/configuration-serveur/roles.md
> +Si L'utilisateur possède plusieurs rôles ayant des badges, seul le badge le plus élevé dans la liste des rôles sera affiché dans les discussions textuelles.
Peut-être faudrait-il remplacer le terme "badge" par "icône de rôles", qui est la nomenclature officielle

2022-09-04 10:18 UTC, volcanofr commented
Je modifie une fois chez moi 👌

2022-09-13 11:01 UTC, IchiiDev commented
Nouvelle MAJ du Wiki, il est nécéssaire d'update votre fork avant de réouvrir une PR

2022-09-13 11:01 UTC, closed without merging