Update message-requests.md
discordfr/wiki pull request #188
Opened 2022-09-21 18:47 UTC by Rodenzow

Création du wiki message request + d'une bannière/asset pour celle-ci.

**Quel est votre identifiant Discord ?**<br/> 
578231146765352970 | 460888867818569739

**Décrivez rapidement vos ajouts ou changements**<br/>
Création du wiki Message Request + Création d'une bannière/asset personnalisé(e) uniquement pour l'article.

2022-09-21 20:07 UTC, grifgrif requested changes
Salut,

Merci de ton article, c'est un bon début,
Je me suis permis de souligner quelques modifications.
Certaines tournures de phrases sont encore trop didacticiels et sont à reprendre.

Si tu as des questions, n'hésite pas.
- GrifGrif

2022-09-21 20:07 UTC, grifgrif commented on interface/appel-message-prives/message-requests.md
> +## Comment désactiver les Demandes de Messages pour les nouveaux serveurs que nous rejoignons ?
... nouveaux serveurs rejoints ?

2022-09-21 20:07 UTC, grifgrif commented on interface/appel-message-prives/message-requests.md
> +![disable_message_request_new_server](https://i.imgur.com/wlEvwNH.png)
https://i.discord.fr/MHnK.png

2022-09-21 20:07 UTC, grifgrif commented on interface/appel-message-prives/message-requests.md
> +![disable_message_request_server](https://i.imgur.com/TBkECqA.png)
https://i.discord.fr/FjNh.png

2022-09-21 20:07 UTC, grifgrif commented on interface/appel-message-prives/message-requests.md
> +![report_spam](https://i.imgur.com/rP1Mh4W.png)
https://i.discord.fr/7vaU.png

2022-09-21 20:20 UTC, Rodenzow commented on interface/appel-message-prives/message-requests.md
> +Les Demandes de Messages sont une nouvelle fonctionnalité, permettant aux utilisateurs de pouvoir être prévenu quand quelqu'un leur envoie un Message Privé. Discord a voulu intégrer cette fonctionnal
Yep effectivement, du coup: 

Les Demandes de Messages **sont une fonctionnalité**, permettant aux utilisateurs de pouvoir être prévenu quand quelqu'un leur envoie un Message Privé.

2022-09-21 20:22 UTC, grifgrif commented on interface/appel-message-prives/message-requests.md
> +Les Demandes de Messages sont une nouvelle fonctionnalité, permettant aux utilisateurs de pouvoir être prévenu quand quelqu'un leur envoie un Message Privé. Discord a voulu intégrer cette fonctionnal
Édite ton commit xD

2022-09-21 20:22 UTC, Rodenzow commented on interface/appel-message-prives/message-requests.md
> +Les Demandes de Messages contiennent plusieurs fonctionnalités toutes différentes, tout d'abord nous pouvons voir deux petites icônes tout à droite, nous permettant d'accepter ou de refuser une Deman
Yep, j'ai voulu raccourcir les mots "Message Privé", mais oui du coup c'est plus compréhensible si nous mettons directement les mots en entier, du coup on peut aussi enlever les `` et mettre à la place de MP, "Message Privé".

2022-09-21 20:25 UTC, Rodenzow commented on interface/appel-message-prives/message-requests.md
> +## Comment désactiver les Demandes de Messages pour les nouveaux serveurs que nous rejoignons ?
Oui, j'ai eu un petit doute sur celui-ci, sur le coup je ne savais pas si je devais mettre "nous", ou bien faire plus court. Mais je préfère ton idée :3.

2022-09-24 21:10 UTC, IchiiDev commented
@Rodenzow des liens d'images t'ont été communiquées, pourrais-tu les changer s'il te plait ? 👍

2022-10-01 10:33 UTC, grifgrif submitted a review, later dismissed
Bonjour,

Je vais surement paraître chiant, mais il y a encore une tournure didacticiel.
Pour rappel, il faut proscrire :
- Étape par étape, guidage.
- Description des emplacements.
- Conseils autres que ceux donnés par des sources officielles (dites premières.)
- Les interactions avec le lecteur/s'adresser directement au lecteur.
- Les tournures de phrases caractéristiques du tutoriel.

Je te remercie encore de la contribution, manque plus que les changements au-dessus et tout est parfait.
GrifGrif.

2024-11-03 13:04 UTC, LukeSkywalkerDev approved these changes

2024-11-03 13:08 UTC, merged