Update threads.md
discordfr/wiki pull request #194
Opened 2022-09-30 17:23 UTC by bariboo

Ajout d'une catégorie "Fils privés".

**Quel est votre identifiant Discord ?**<br/> 
Entrez votre ID ici

**Décrivez rapidement vos ajouts ou changements**<br/>
Entrez votre description ici

2022-09-30 22:39 UTC, justsomebigsock commented on interface/salons-textuels/threads.md
> +Un thread privé est un thread où il faut inviter la personne pour qu'elle y ait accès. Cocher la case (voir image) pour le rendre privé.
Je ne pense pas qu'il est nécessaire de préciser "voir image"

2022-10-01 10:13 UTC, grifgrif requested changes
Bonjour,
Apports pertinents, des modifications doivent y êtres apportés.
Il ne faut pas non plus faire de didacticiel.
Pour rappel, il faut proscrire :
- Étape par étape, guidage.
- Description des emplacements.
- Conseils autres que ceux donnés par des sources officielles (dites premières.)
- Les interactions avec le lecteur/s'adresser directement au lecteur.
- Les tournures de phrases caractéristiques du tutoriel.

Merci encore de votre contribution.

À bientôt,
GrifGrif.

2022-10-01 10:13 UTC, grifgrif commented on interface/salons-textuels/threads.md
> +Il faut que le server soit boost level 2 pour avoir accès à cette fonctionnalitée.
Met un lien sur le wiki de boost serveur.

2022-10-01 10:13 UTC, grifgrif commented on interface/salons-textuels/threads.md
> +![Création fils privé](https://imgur.com/deLHAWn)
https://i.discord.fr/s1pt.png

2022-10-01 10:15 UTC, grifgrif commented on interface/salons-textuels/threads.md
> +Un thread privé est un thread où il faut inviter la personne pour qu'elle y ait accès. Cocher la case (voir image) pour le rendre privé.
Effectivement !

2022-10-01 10:28 UTC, IchiiDev commented on interface/salons-textuels/threads.md
> +Il faut que le server soit boost level 2 pour avoir accès à cette fonctionnalitée.
La phrase pourrait également être mieux écrite. Et il faudrait également modifié la faute "server" -> "serveur"

2022-10-01 18:02 UTC, bariboo commented on interface/salons-textuels/threads.md
> +![Création fils privé](https://imgur.com/deLHAWn)
Hey ! J'attend actuellement que une personne me donne la permission de pouvoir crée des fils privés pour que j'étudie un peu plus le sujet, je reviens vers vous dès que j'ai fait ça !
Bonne soirée

2023-01-31 13:39 UTC, closed without merging

2023-01-31 13:40 UTC, bariboo commented
Au vu du temps attendu et au modification apportée par discord sur ce sujet, j'en recréerai une une fois les changements seront apportées sur le wiki.