Update abonnements-nitro.md
discordfr/wiki pull request #196
Opened 2022-10-17 23:50 UTC by Thims24

J'ai juste ajouté une section sur le futur plan Nitro Basic, j'essaierai de la mettre à jour assez régulièrement en fonction des nouveautés (je suis activement les nouveautés de Discord), et j'ai rajouté un mot-clé : "basic".

Je n'ai fait aucune autre modification en dehors de cette section (excepté le mot-clé).

Source des informations : 

 - https://discord.com/blog/introducing-discord-nitro-basic
 - https://support.discord.com/hc/en-us/articles/7327393982487-Nitro-Basic-Plan

Merci

**Quel est votre identifiant Discord ?**<br/> 
843424320537231360

**Décrivez rapidement vos ajouts ou changements**<br/>
J'ai juste ajouté une section sur le futur plan Nitro Basic, j'essaierai de la mettre à jour assez régulièrement en fonction des nouveautés (je suis activement les nouveautés de Discord), et j'ai rajouté un mot-clé : "basic".

Je n'ai fait aucune autre modification en dehors de cette section (excepté le mot-clé).

2022-10-17 23:50 UTC, d-fr commented
Salut ! Une partie de l'équipe sera indisponible jusqu'au mois de Novembre, ce qui va entrainer un délai de traitement des Pull Request. La reprise progressive des vérifications à un rythme normal est prévue à partir du 7 Novembre.

2022-10-19 15:45 UTC, IchiiDev requested changes
Beaucoup de choses à revoir, notamment concernant la façon de rédiger et de présenter les informations. 
Je t'invite donc à relire [les règles de contribution du Wiki](https://github.com/discordfr/wiki#r%C3%A8gles-de-r%C3%A9daction-et-de-mise-en-forme) afin de connaitre nos attentes.

Les points que je peux souligner sont les suivants:
- Le wiki n'est pas un blog, merci d'éviter de vous addresser au lecteur et de rester neutre dans la rédaction.
- Tout pointeur de temps ou rédaction faisant explicitement référence au fait qu'une feature arrive, n'est pas conseillé, traitez le sujet comme si il était bel et bien présent sur Discord.

Bonne rédaction !

2022-10-19 16:38 UTC, Thims24 commented
Désolé mais je ne sais absolument pas comment fonctionne Github, je ne suis quasiment jamais dessus.

2022-10-26 07:15 UTC, IchiiDev commented
Bonjour, vous avez une semaine pour mettre à jour votre Pull Request, sans quoi elle sera fermée faute d'activité. ([Voir les règles de contribution du wiki](https://github.com/discordfr/wiki#r%C3%A8gles-de-contribution))
Vous pouvez lire le README du wiki afin de comprendre comment contribuer efficacement.

2022-10-28 15:51 UTC, closed without merging