Update personnalisation-profil.md
discordfr/wiki pull request #224
Opened 2024-04-21 11:31 UTC by AntoineGigleux

**Quel est votre identifiant Discord ?**<br/> 
1081649566618759218

**Décrivez rapidement vos ajouts ou changements**<br/>
Modification du point "Rouge" à propos des noms d'utilisateur

2024-04-21 11:31 UTC, d-fr commented
Salut ! Une partie de l'équipe sera indisponible jusqu'au mois de Novembre, ce qui va entrainer un délai de traitement des Pull Request. La reprise progressive des vérifications à un rythme normal est prévue à partir du 7 Novembre.

2024-12-25 20:08 UTC, volcanofr commented
Bonjour/bonsoir !
Merci d'apporter ta contribution à Discord FR !

Quelques points sur la modification de la page sont, cependant, à revoir.
L'image doit être changée pour s'adapter à la mise à jour de Discord.

Je trouverai aussi pertinent de parler séparément des noms d'utilisateur & d'affichage. Ainsi que d'en dire sur les décorations d'avatar et les effets de profil.

2025-03-09 22:32 UTC, volcanofr requested changes
Tes modifications sur la tournure des phrases est superbe !

Quelques ajouts sont, cependant, à jouter :
- Les liens vers les pages liées
- Les nouvelles fonctionnalités de Discord vis-à-vis des profils (nom d'affichage, cosmétiques, etc...)

2025-03-09 22:32 UTC, volcanofr commented on compte-utilisateur/personnalisation-profil/personnalisation-profil.md
> +![Profil](https://i.dfr.gg/xfc7.png)
L'image doit être mise à jour. Ce profil, utilisant un tag (`#0000`), n'est plus disponible aux utilisateurs de l'application.

2025-03-09 22:32 UTC, volcanofr commented on compte-utilisateur/personnalisation-profil/personnalisation-profil.md
> +- **Vert:** La bannière de profil est une image personnalisée ou une couleur.
Le **lien était correct** (`/wiki/compte-utilisateur/personnalisation-profil/bannieres-avatars`). Il est positif de garder des redirections vers d'autres pages du wiki (même si c'est dans la même catégorie) ou du blog.

Une alternative au lien serait de placer une [DocCardList](https://docusaurus.io/docs/2.x/sidebar/items#embedding-generated-index-in-doc-page) en bas de la page.

Sur **la formulation**, aussi, c'est l'image et la couleur qui sont personnalisables. La phrase est actuellement tournée d'une manière où l'on peu comprendre que la couleur n'est pas modifiable.

2025-03-09 22:32 UTC, volcanofr commented on compte-utilisateur/personnalisation-profil/personnalisation-profil.md
> +- **Jaune:** Les badges de profil sont la preuve d'appartenance à un programme communautaire de Discord et d'implication d'un utilisateur sur l'application.
De même, un lien devrait être disponible sur la page.

2025-03-09 22:32 UTC, volcanofr commented on compte-utilisateur/personnalisation-profil/personnalisation-profil.md
> +- **Violet:** Le statut personnalisé est un élément défini par l'utilisateur qui s'affiche lorsqu'il n'est pas hors ligne ou en invisible.
De même, un lien devrait être disponible sur la page.

2025-03-09 22:32 UTC, volcanofr commented on compte-utilisateur/personnalisation-profil/personnalisation-profil.md
> +- **Rouge:** Le nom de compte Discord est composé d'un nom d'utilisateur unique composé uniquement de lettres, de chiffre, de tirets du bas ou de points.
Il serait aussi utile de décrire quelque part ce qu'est les noms d'affichage.

2025-08-07 13:57 UTC, closed without merging