Update discovery.md
discordfr/wiki pull request #230
Opened 2024-04-23 20:11 UTC by AntoineGigleux

**Quel est votre identifiant Discord ?**<br/> 
1081649566618759218

**Décrivez rapidement vos ajouts ou changements**<br/>
Ajout des informations, modification de la page

2024-04-23 20:11 UTC, d-fr commented
Salut ! Une partie de l'équipe sera indisponible jusqu'au mois de Novembre, ce qui va entrainer un délai de traitement des Pull Request. La reprise progressive des vérifications à un rythme normal est prévue à partir du 7 Novembre.

2024-05-27 14:04 UTC, IchiiDev requested changes

2024-05-27 14:04 UTC, IchiiDev commented on gestion-serveur/outils-communautaires/discovery.md
> +* Une A2F obligatoire pour la modération activée
Une A2F obligatoire activée pour les utilisateurs ayant des permissions de modération

2024-05-27 14:04 UTC, IchiiDev commented on gestion-serveur/outils-communautaires/discovery.md
> +* Avoir un serveur vieux de 8 semaines
D'au moins 8 semaines

2025-08-07 13:57 UTC, closed without merging