Create webhooks.md
discordfr/wiki pull request #232
Opened 2024-04-25 18:10 UTC by AntoineGigleux

**Quel est votre identifiant Discord ?**<br/> 
1081649566618759218

**Décrivez rapidement vos ajouts ou changements**<br/>
Ajout de la page

2024-04-25 18:10 UTC, d-fr commented
Salut ! Une partie de l'équipe sera indisponible jusqu'au mois de Novembre, ce qui va entrainer un délai de traitement des Pull Request. La reprise progressive des vérifications à un rythme normal est prévue à partir du 7 Novembre.

2024-05-27 13:46 UTC, IchiiDev requested changes

2024-05-27 13:46 UTC, IchiiDev commented on webhooks.md
> +Un Webhook est une intégration au sein d'un serveur, permettant à des outils externes d'envoyer des messages sur un serveur. Le webhooks fonctionne graçe à une URL à placer sur l'outil externe.
`graçe` -> `grace`
Les webhooks fonctionnent grace à une URL fournie au service externe, qui l'utilisera pour envoyer des messages.

2024-05-27 13:46 UTC, IchiiDev commented on webhooks.md
> +Les webhooks peuvent représenter un danger. En cas de divulgation d'un lien de webhook, celui-ci peut devenir une porte d'entrée pour des attaques de serveur. Étant en mesure d'envoyer des messages v
Un envoi*

2024-05-27 13:46 UTC, IchiiDev commented on webhooks.md
> +Le type de message que le webhooks envoie peut varier en fonction de ce qui est utilisé. Les messages peuvent être automatique et même manuel comme avec discohook.
le webhook* au singulier dans la phrase

2024-05-27 13:46 UTC, IchiiDev commented on webhooks.md
> +[Discohook](https://discohook.org/) représente un outil externe parmi de nombreux autres qui permettent l'envoi de messages par la voie des webhooks mais de façon manuelle.
Discohook est un outil externe

2024-05-27 13:46 UTC, IchiiDev commented on webhooks.md
> +Le type de message que le webhooks envoie peut varier en fonction de ce qui est utilisé. Les messages peuvent être automatique et même manuel comme avec discohook.
Pourquoi parler de discohook ici et puis à la ligne suivante ?

2025-08-07 13:57 UTC, closed without merging