Update outils-communautaires.md
discordfr/wiki pull request #240
Opened 2024-08-06 19:41 UTC by AntoineGigleux

**Quel est votre identifiant Discord ?**<br/> 
1081649566618759218

**Décrivez rapidement vos ajouts ou changements**<br/>
Cout de neuf, réorganisation de la page-catégorie.

2024-08-06 19:50 UTC, AntoineGigleux commented
Réorganisation de la page catégorie. 

```diff
- suppression de l'intégralité des avantages de cette page *
+ images remise à jour
+ textes remis à jour
```

* Le fait de retirer tous les avantages épure la page qui n'est qu'une page de présentation de ce qui suit. Chaque fonctionnalité sera donc détaillée dans une page dédiée dans la catégorie. Rien ne sert de mettre toutes les informations sur une seule page, surtout quand celle-ci ne sert qu'à présenter la suite. 
Il faut de ce fait faire une page pour chaque fonctionnalité, à savoir :

- Analyses de serveur (déjà créé, à mettre à jour si besoin) 
- L'écran d'accueil / Onboarding
- Les salons d'annonces, forum et conférence
- Discovery (J'ai un doute si elle n'a pas été déjà faite : à regarder dans le wiki et dans les pulls request, elle doit peut-être y être) 
- ...

2024-08-16 16:14 UTC, LukeSkywalkerDev requested changes
Hello, 

Quelques modifications doivent encore être apportées (notamment sur la forme), mais je partage ton idée de supprimer les avantages de la page.

Luke

2024-08-16 16:23 UTC, AntoineGigleux commented
Tu penses à quoi la tout de suite en terme de forme ?

2024-08-16 16:49 UTC, LukeSkywalkerDev commented
À ce que j'ai indiqué sur le serveur Discord : mettre au pluriel "de nouvelle option de gestion" -> "de nouvelles options de gestion" et retirer les virgules entre le mot "également" et ceux qui l'entoure

2025-08-07 13:57 UTC, closed without merging