Fix markdown.mdx
discordfr/wiki pull request #242
Opened 2024-09-01 13:24 UTC by volcanofr

**Quel est votre identifiant Discord ?**

589383722759880705

**Décrivez rapidement vos ajouts ou changements**

Fix sur les raccourcis clavier : le soulignage apparaissait alors que le gras et l'italique non.
> https://dfr.gg/wiki/interface/salons-textuels/markdown#raccourcis

2024-09-01 14:47 UTC, LukeSkywalkerDev requested changes
Hello,

Merci pour ta contribution !

La balise \<u> ne fonctionne apparemment sur Github pour souligner du texte : je te conseille donc de la remplacer par `\<p style="text-decoration: underline">Hey</p>.

Une fois ce problème résolu, la PR pourra être merged au wiki.

Belle après-midi,
Luke

2024-09-07 07:09 UTC, volcanofr commented
Coucou,

Le but final n'est de toute façon pas Github, mais Docusaurus.
Donc je ne vois pas trop où est le problème...
Je peux quand même le faire mais je ne pense pas que l'intérêt y soit. Dois-je quand même le faire ?

Bonne journée,
volcano

2024-09-07 08:05 UTC, LukeSkywalkerDev commented
Hello,

Yep je sais, mais ça aurait permis d'avoir à la fois le résultat sur le wiki et sur la preview de Github. L'important est que le résultat soit propre sur le wiki donc je vais merge ta PR.

Belle journée,
Luke

2024-09-07 08:07 UTC, LukeSkywalkerDev approved these changes

2024-09-07 08:08 UTC, merged