Update message-systeme.md
discordfr/wiki pull request #250
Opened 2024-12-29 23:17 UTC by volcanofr

**Quel est votre identifiant Discord ?**<br/> 
589383722759880705

**Décrivez rapidement vos ajouts ou changements**<br/>
Précisions rajoutées dans le warning.

2025-01-09 08:41 UTC, LukeSkywalkerDev requested changes
Hello,

C'est bon pour moi, à l'exception de deux petits points que l'on pourrait à mon sens un peu davantage clarifier. 

Pourras-tu également corriger les fautes d'orthographe ligne 19 : "En bas des messages privées" remplacé par "En dessous des messages privés", voire "Sous la discussion" et l. 21 et 23 : "banière" -> "bannière".

Belle journée à toi :)

2025-01-09 08:41 UTC, LukeSkywalkerDev commented on confiance-securite/message-systeme.md
> +Seul les messages des utilisateurs @`discord` et @`discordupdates` sont officiels.
Une petite faute d'orthographe ici : "seul **s** "

2025-01-09 08:41 UTC, LukeSkywalkerDev commented on confiance-securite/message-systeme.md
> +**Tout autre compte prétendant être Discord peu être considéré comme faux** et ayant un caractère frauduleux.
On pourrait reformuler la phrase ainsi : "Tout autre compte se présentant comme affilié avec Discord peut être considéré comme frauduleux. Discord ne contacte jamais les utilisateurs par l'intermédiaire de comptes non officiels." 

Je pense qu'en le formulant de cette façon là, on pose directement les enjeux et on y ajoute une explication. Qu'en penses-tu ?

2025-01-18 20:15 UTC, volcanofr commented
Oh no...
[volcanofr](https://github.com/volcanofr) added 2 commits

2025-01-18 20:28 UTC, volcanofr commented
Hope, soucis réglé 👀
Plus qu'à fix les changements requis.

2025-02-04 19:08 UTC, LukeSkywalkerDev approved these changes
Merci pour les modifications que tu as apportées à cette page ! C'est bon pour moi ;)

2025-02-04 19:08 UTC, merged