Update salons-textuels.md
discordfr/wiki pull request #46
Opened 2021-01-16 13:59 UTC by Brewen22

Création de la page.

2021-01-16 14:16 UTC, IchiiDev commented
C'est un bon début, malgré tout il faudrait faire des reformulations, voici ce que je préconise:
- Abordez une approche informative plus qu'indicative, un Wiki est une banque d'information et non pas un tutoriel, ne vous adressez pas au lecteur et veuillez énoncer des informations plutôt que de suivre des étapes.
- Certaines tournures de phrases sont lourdes et il serait préférables de les corrige.
- Évitez de répéter trop de fois le mot salon, même si c'est le sujet principal de l'article il vaut mieux trouver des périphrases adéquates.

2021-01-16 15:06 UTC, Brewen22 commented
D'accord^^
Je vais modifier un peu l'article en tenant compte de vos conseils ;) 
Voici mon ID Discord comme vous l'avez demandé : 678550943033327628
Je reviens vers vous après avoir modifié l'article,
Cordialement.

2021-01-16 15:25 UTC, Brewen22 commented
Et voilà :) 
Sa fait un peut moins "tuto".
Cordialement

2021-01-16 15:45 UTC, IchiiDev requested changes
Il reste encore des changements à effectuer, comme reformuler les phrases pour ajouter du sens. Raccourcir les informations à certains endroits ou utiliser des listes pour énumérer des informations dans le but d'alléger le texte. Pour garder une hiérarchie des titres correcte, utilisez des titres de niveau 2 et non de niveau 3 (Le titre de l'article est au niveau 1)

2021-01-16 15:45 UTC, IchiiDev commented on interface/salon-textuel/salons-textuels.md
> +Un peu à droite de la description, vous avez une cloche qui vous permet d'activer/de désactiver les notifications de ce salon là précis (si vous êtes mentionnés dans un message, vous recevrez quant m
Emploi du pronom personnel "vous" à éviter

2021-01-16 15:45 UTC, IchiiDev commented on interface/salon-textuel/salons-textuels.md
>  ![Exemple création](https://media.discordapp.net/attachments/799991913821241355/799994851470737438/unknown.png)
Lien permanent: https://i.discord.fr/De7.png

2021-01-16 15:45 UTC, IchiiDev commented on interface/salon-textuel/salons-textuels.md
>  ![Exemple mention](https://media.discordapp.net/attachments/799991913821241355/799993035789434930/unknown.png)
Lien permanent: https://i.discord.fr/alO.png

2021-01-16 15:45 UTC, IchiiDev commented on interface/salon-textuel/salons-textuels.md
> +Il est possible d'en mentionner  dans un message en écrivant simplement son nom précédé d'un dièse, ce qui aura pour effet que n'importe qui pourra accéder au salon à partir de la mention (seulement
La formulation "que n'importe qui pourra accéder au salon à partir de la mention" est correcte mais pourrait être remplacée par "que n'importe quel utilisateur aura accès au salon depuis la mention"

2021-01-16 15:45 UTC, IchiiDev commented on interface/salon-textuel/salons-textuels.md
> +Le nom de celui-ci est toujours écrit en minuscule et les espaces afin de séparer les mots sont toujours des traits d'union ( - )
La formulation précédente était correcte vu que c'était la première mention du mot "salon" dans l'article

2021-01-16 16:20 UTC, IchiiDev commented on interface/salon-textuel/salons-textuels.md
> +Pour en créer un , il faut tout d'abord faire un clic droit sur la liste des salons, puis faire un clic gauche sur Créer un salon, ou alors faire un clic gauche sur le plus (+) à côté d'une Catégorie
Merci de reformuler cette ligne pour ne pas sonner comme un tutoriel

2021-01-16 16:22 UTC, IchiiDev requested changes
J'ai corrigé des erreurs dans mon commit, je vous laisse également prendre connaissances de mes commentaires puis relire votre article afin de déceler les dernières fautes.

2021-01-17 09:53 UTC, Brewen22 commented
Voilà ;)

2021-01-19 19:46 UTC, IchiiDev requested changes
Il reste des formules indicatives ligne 26 ainsi que des fautes de frappes et de ponctuation à corriger, je ferait un check complet après ça

2021-01-20 18:33 UTC, Brewen22 commented
J'ai supprimé la dernière phrase de la ligne 26 car elle est inutile, je pense que c'est logique.
J'ai aussi corriger mes fautes de ponctuation.
Voilà, je pense avoir fait le tour et ne plus avoir de fautes, je vous laisse faire le check final.
Passez une bonne soiré, Brewen

2021-01-22 17:01 UTC, IchiiDev commented
La pull request #51 est plus completè, nous allons la merge, n'hésitez pas à contribuer à l'article créé pour cette pull request si vous voyez des choses à modifier ou ajouter.

2021-01-22 17:01 UTC, closed without merging