Création de emojis-et-reactions.md
discordfr/wiki pull request #52
Opened 2021-01-20 09:26 UTC by LukeSkywalkerDev

Hello !
Je n'ai pas utilisé de sources pour cet article.
Bonne relecture !

2021-01-22 16:59 UTC, IchiiDev requested changes
Il y a quelques changements à faire, mais c'est déjà un bon début

2021-01-22 16:59 UTC, IchiiDev commented on interface/salon-textuel/emojis-et-reactions.md
> +# Les emojis et les réactions sur Discord
Vous devriez éviter à l'avenir de rajouter un titre de niveau 1 car celui-ci est déjà ajouté par le site (Nom de l'article)

2021-01-22 16:59 UTC, IchiiDev commented on interface/salon-textuel/emojis-et-reactions.md
> +Comme bien d'autres plateformes de discussion, des emojis par défaut sont présents sur Discord. Ces emojis sont utilisables sur n'importe quel serveur par n'importe qui sans restriction.
Vous pouvez peut-être ajouter que ce sont les émojis unicode qui ont été stylisés

2021-01-22 16:59 UTC, IchiiDev commented on interface/salon-textuel/emojis-et-reactions.md
> + :::
Les deux lignes pourraient être reformulées en une pour éviter les répétitions

2021-01-23 09:42 UTC, LukeSkywalkerDev commented on interface/salon-textuel/emojis-et-reactions.md
> +# Les emojis et les réactions sur Discord
oki, je ne savais pas qu'il était déjà inclus ! Je prends note de votre remarque ;)

2021-01-23 10:00 UTC, LukeSkywalkerDev commented
C'est modifié !

2021-01-26 15:39 UTC, IchiiDev reviewed
Désolé pour le retard dans la review. Tout m'a l'air correct, on a vérifié les fautes de notre côté. Paré à merge !

2021-01-26 15:39 UTC, IchiiDev approved these changes

2021-01-26 15:40 UTC, merged