Modification de permissions.md
discordfr/wiki pull request #59
Opened 2021-03-03 08:23 UTC by Feoxy

J'ai rajouté la nouvelle permission "Use Slash command"

2021-03-03 12:23 UTC, IchiiDev requested changes
Merci de changer ce qui a été pointé dans les commentaires

2021-03-03 12:23 UTC, IchiiDev commented on configuration-serveur/permissions/textuelles.md
> +![Permission](https://i.imgur.com/fXTCXnN.png)
Lien recommandé https://i.discord.fr/R88.png

2021-03-03 12:23 UTC, IchiiDev commented on configuration-serveur/permissions/textuelles.md
> +Les membres ayant cette permission peuvent utiliser les slashs commandes dans les salons textuels
"slashs commandes" n'est pas correct, nous vous conseillons d'étoffer un peu et de les présenter sous l'appellation "Commandes Slash"  par exemple

2021-03-03 12:59 UTC, Feoxy commented
Je viens de modifier, cela est bon ?

2021-03-06 12:14 UTC, Feoxy commented on configuration-serveur/permissions/textuelles.md
> +![Permission](https://i.imgur.com/fXTCXnN.png)
Cela est fait

2021-03-06 12:14 UTC, Feoxy commented
Faut il faire d'autres modifications ?

2021-03-06 13:10 UTC, IchiiDev requested changes

2021-03-06 13:10 UTC, IchiiDev commented on configuration-serveur/permissions/textuelles.md
> +![Exemple](https://i.imgur.com/LF324aS.png)
Pas besoin d'exemple, on présente les permissions pas les commandes slash.

2021-03-06 13:14 UTC, Feoxy commented on configuration-serveur/permissions/textuelles.md
> +![Exemple](https://i.imgur.com/LF324aS.png)
D'accord Je retire cela

2021-03-06 13:15 UTC, Feoxy commented
Et voilà c'est modifié !

2021-03-06 14:02 UTC, IchiiDev approved these changes
La correction est valide

2021-03-06 14:02 UTC, merged