Update de partage-video.md
discordfr/wiki pull request #60
Opened 2021-03-07 10:38 UTC by Feoxy

Je viens de faire la page **partage-video.md**

2021-03-07 12:13 UTC, PixelNotix requested changes
- Vous ne précisez pas comment utiliser la fonction Vidéo sur Ordinateur.
- Il serait préférable de mieux détourer vos captures d'écrans. (il est facile de le faire avec un outil comme Paint.Net ou bien ShareX.)
- Vous devez employer une formulation indicative (pas de "vous").

2021-03-07 17:32 UTC, Feoxy commented
Voilà je viens de faire les modifications nécessaires

2021-03-15 20:21 UTC, IchiiDev requested changes
Plusieurs points sont à corriger:
- Ne pas utiliser de titres à tort, vous en utilisez pour la quasi totalité du contenu.
- Vous prenez une approche trop didactique et ne vous focalisez pas sur la rédaction d'une banque de donnée, gardez en tête que ce wiki n'est en aucun cas un guide
- Les descriptions d'image n'ont aucun sens, il serait judicieux de les éditer

2021-03-20 17:05 UTC, Feoxy commented
> Plusieurs points sont à corriger:
> 
> * Ne pas utiliser de titres à tort, vous en utilisez pour la quasi totalité du contenu.
> * Vous prenez une approche trop didactique et ne vous focalisez pas sur la rédaction d'une banque de donnée, gardez en tête que ce wiki n'est en aucun cas un guide
> * Les descriptions d'image n'ont aucun sens, il serait judicieux de les éditer

Voilà je viens de faire les modifications nécessaires

2021-03-20 22:32 UTC, IchiiDev requested changes
Vous restez trop dans une approche de guide, ce qui n'est pas le but de ce wiki, je vous prie de revoir la formulation de votre article pour ne pas faire de tutoriel.

2021-03-20 22:32 UTC, IchiiDev commented on interface/salon-vocal/partage-video.md
> +#### ⚠️ Attention ! *La fonction changer de sens* marche que sur **Un Téléphone Portable.**
Préférez l'utilisation des bulles d'information pour ce genre de précisions et non pas des titres: [Admonitions - Docusaurus](https://v2.docusaurus.io/docs/markdown-features/admonitions)

2021-03-21 10:37 UTC, Feoxy commented on interface/salon-vocal/partage-video.md
> +#### ⚠️ Attention ! *La fonction changer de sens* marche que sur **Un Téléphone Portable.**
D'accord je fais les modifications dès que possible

2021-03-21 17:43 UTC, Feoxy commented on interface/salon-vocal/partage-video.md
> +#### ⚠️ Attention ! *La fonction changer de sens* marche que sur **Un Téléphone Portable.**
voilà je viens de faire les modifications !

2021-03-22 11:04 UTC, IchiiDev requested changes
Plusieurs erreurs à pointer:
- Restez neutre, ne faites pas de phrase type "Il n'y a plus de limite pour s'amuser !"
- Ne vous adressez pas à l'utilisateur
- Ne faites pas d'étapes, vous utilisez la formulation "une fois la configuration terminée" et cela ne convient pas
- Vos images ne sont pas les plus récentes ou sont pour certaines invalides, revérifiez les.

Cette pull request sera fermée suite à de nombreuses reviews infructueuses, vous devrez en rouvrir une après avoir revu votre article.

2021-03-22 11:04 UTC, closed without merging