Update groupes-prives.md
discordfr/wiki pull request #71
Opened 2021-05-07 17:27 UTC by XoxFR

**Quel est votre ID Discord ?**<br/>
ID: 320503214229291008

**Décrivez rapidement vos changements**<br/>
Rédaction d'un article sur les groupes privés.

2021-05-07 17:44 UTC, IchiiDev requested changes
Merci de ne pas vous adresser directement à l'utilisateur. Ceci est un wiki et non pas un tutoriel. Cherchez à expliquer de façon informative plutôt que didactique.
Essayez également de garder une hiérarchie des textes correctes (Utilisez des titres de niveau 2 avant d'utiliser des trois)

2021-05-07 18:41 UTC, XoxFR commented
Voilà, ça devrait être mieux maintenant.

2021-05-13 18:00 UTC, IchiiDev requested changes

2021-05-14 13:55 UTC, IchiiDev approved these changes
LGTM, normalement ça devrait être bon, nous ferons probablement de nouveaux screenshots dans le futur. 
Nous t'avons attribué le rôle contributeur sur Slash FR, félicitation ! :)

2021-05-14 13:55 UTC, merged