Update notification-serveurs.md
discordfr/wiki pull request #78
Opened 2021-05-17 16:39 UTC by XoxFR

**Quel est votre ID Discord ?**<br/>
ID: 320503214229291008

**Décrivez rapidement vos changements**<br/>
Article sur les notifications par serveur

2021-05-17 20:02 UTC, IchiiDev requested changes

2021-05-18 07:11 UTC, XoxFR commented on parametres-compte/notifications/notification-serveurs.md
> +Les notifications par serveur permettent de personnaliser les "pings" que l'on souhaite recevoir, très pratique pour ne pas être saturé de notifications.
Malheureusement je ne sais quel autre terme choisir pour éviter une répétition. 
"Les notifications par serveur permettent de personnaliser celles que l'on souhaite recevoir sur chaque serveur, très pratique pour ne pas être saturé de notifications." pourrait marcher ?

2021-05-18 07:14 UTC, IchiiDev commented on parametres-compte/notifications/notification-serveurs.md
> +Les notifications par serveur permettent de personnaliser les "pings" que l'on souhaite recevoir, très pratique pour ne pas être saturé de notifications.
De préférence oui, ça serait mieux, "ping" est de plus un terme trop "familier" ou des fois pas assez commun pour être explicite aux yeux des lecteurs.

2021-05-18 11:38 UTC, IchiiDev commented on parametres-compte/notifications/notification-serveurs.md
> +Les notifications par serveur permettent de personnaliser celles que l'on souhaite recevoir sur chacun de ceux sur lesquels on se trouve, très pratique pour ne pas être saturé de notifications.
Je propose cette tournure de phrase: "Les notifications par serveur permettent aux utilisateurs de personnaliser les notifications qu'ils souhaitent recevoir sur chacun de leurs serveurs. Très pratique pour ne pas être saturé de notifications."

2021-05-18 11:39 UTC, XoxFR commented on parametres-compte/notifications/notification-serveurs.md
> +Les notifications par serveur permettent de personnaliser celles que l'on souhaite recevoir sur chacun de ceux sur lesquels on se trouve, très pratique pour ne pas être saturé de notifications.
Yup, c'est bien mieux

2021-05-18 19:30 UTC, IchiiDev approved these changes
LGTM

2021-05-18 19:31 UTC, merged