Update partage-video.md
discordfr/wiki pull request #79
Opened 2021-05-19 15:20 UTC by LukeSkywalkerDev

Hey !

J'ai utilisé cet article de Discord pour la vidéo : https://support.discord.com/hc/fr/articles/360041721052-Vid%C3%A9o-serveur

Bonne relecture :D

**Quel est votre ID Discord ?**<br/>
ID:

**Décrivez rapidement vos changements**<br/>
Entrez votre description ici

2021-05-20 16:10 UTC, BenNotix requested changes
* Nous vous demandons d'utiliser une formulation plus informative et soutenue. Veillez également à vous relire avant d'effectuer votre pull request. À certains endroits dans votre article, nous pouvons observer des espaces manquants, ou bien des espaces en trop (exemple à la ligne n°18).
* Concernant vos images, faites également en sorte qu'elles soient correctement détourées. (pour vos prochains articles, vous pourrez vous aider de [l'outil permettant de récupérer les assets de Discord](https://github.com/Commandtechno/discasset)).

2021-05-20 16:11 UTC, BenNotix commented on interface/salon-vocal/partage-video.md
> +![Vue sous forme de grille](https://i.discord.fr/Ya7.png)
Vous pouvez remplacer cette image avec celle-ci: https://i.discord.fr/NoE.png

2021-05-20 16:12 UTC, BenNotix commented on interface/salon-vocal/partage-video.md
> +![Vue sous forme focalisée](https://i.discord.fr/8CY.png)
Vous pouvez remplacer cette image avec celle-ci: https://i.discord.fr/WzO.png

2021-05-20 16:14 UTC, BenNotix commented on interface/salon-vocal/partage-video.md
> +![Image de la fenêtre](https://i.discord.fr/QzI.png)
Cette image n'est pas conforme. Nous voyons qu'elle a été modifiée.

2021-05-22 09:27 UTC, LukeSkywalkerDev commented on interface/salon-vocal/partage-video.md
> +![Image de la fenêtre](https://i.discord.fr/QzI.png)
Effectivement, j'en ai remise une plus "propre".

2021-05-22 09:48 UTC, LukeSkywalkerDev commented
J'ai reformulé une bonne partie de l'article, modifié les images concernées et corrigé les espaces manquants/excessifs. J'étais pourtant sûr d'avoir tout vu lors de ma relecture, je suis navré.
Merci pour le lien vers l'outil pour récupérer les assets, c'est effectivement très pratique.

2021-05-27 20:35 UTC, BenNotix approved these changes

2021-05-27 20:35 UTC, merged