Update connexion-officielle.md
discordfr/wiki pull request #80
Opened 2021-05-19 16:07 UTC by LukeSkywalkerDev

Hey ! 

Voilà l'article sur les connexions officielles, j'ai fait avec mes connaissances en essayant d'être le plus exhaustif possible.

Bonne relecture :)

**Quel est votre ID Discord ?**<br/>
ID: 585166080071172098

**Décrivez rapidement vos changements**<br/>
J'ai écrit l'article sur les connexions.

2021-05-20 07:22 UTC, IchiiDev requested changes
J'ai effectué des corrections et reformulations, notamment au niveau des descriptions de chaque plateforme, elles avaient l'air sorties tout droit de Wikipedia et n'étaient pas vraiment compréhensibles pour tout utilisateur ou semblaient tout simplement erronées.

2021-05-20 07:22 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Les connexions permettent à un utilisateur d'afficher sur son profil les applications avec lesquelles son compte est relié.
Soyez un peu plus descriptif, les connexions officielles sont surtout des plateformes et réseaux sociaux/jeux que les utilisateurs peuvent relier à leur compte pour les afficher sur leur profil ou synchroniser des données entre leur compte et la plateforme en question. À ne pas confondre avec les applications OAuth2 qui elles ne sont pas officielles et sont maintenues par des plateformes tierces.

2021-05-20 07:22 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +<img alt="Affichage de la connexion sur le profil" src="https://i.discord.fr/dGx.png" height="" width="600px">
Utilisez une formulation markdown pour les images.

2021-05-20 07:22 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +#### Désactiver l'affichage sur le profil
Utilisez une hiérarchie des titres correcte, merci de ne pas utiliser de titre de niveau 4 après un 2.

2021-05-20 07:22 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Il est par ailleurs possible de suppripmer à tout moment la connexion dans l'onglet "Connexions" des paramètres de l'utilisateur, en cliquant simplement sur la petite croix :
Une faute à corriger ici !

2021-05-20 08:04 UTC, LukeSkywalkerDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +# Les connexions officielles sur Discord
Je l'ai enlevée

2021-05-20 08:06 UTC, LukeSkywalkerDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Les connexions permettent à un utilisateur d'afficher sur son profil les applications avec lesquelles son compte est relié.
ouep je sais, mais j'ai utilisé le mot "applications" comme synonyme  + j'ai ajouté une description globale des connexions possibles

2021-05-20 08:12 UTC, LukeSkywalkerDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +<img alt="Affichage de la connexion sur le profil" src="https://i.discord.fr/dGx.png" height="" width="600px">
j'ai utilisé un titre de niveau 4 parce que je trouvais qu'il était plus approprié ici, mais je vais modifier ça

2021-05-20 08:12 UTC, LukeSkywalkerDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +<img alt="Affichage de la connexion sur le profil" src="https://i.discord.fr/dGx.png" height="" width="600px">
j'ai utilisé une formulation html parce que j'ai redimensionné l'image

2021-05-20 10:25 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Les connexions permettent à un utilisateur d'afficher sur son profil les applications avec lesquelles son compte est relié.
Il convient tout de même de changer cette phrase

2021-05-20 10:26 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Il s'agit principalement de réseaux sociaux, de plateformes de streaming ainsi que de jeux. Ces connexions sont officielles, et ne sont pas à confondre avec les [applications tierces](https://discord
Ce paragraphe peut notamment servir d'introduction à l'article

2021-05-20 10:28 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Il s'agit principalement de réseaux sociaux, de plateformes de streaming ainsi que de jeux. Ces connexions sont officielles, et ne sont pas à confondre avec les [applications tierces](https://discord
Aussi, ne pas confondre, Discord n'est pas en partenariat avec toutes les plateformes, ils ont juste intégré leur API OAuth2 quand cela était possible.

2021-05-20 10:28 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +<img alt="Affichage de la connexion sur le profil" src="https://i.discord.fr/dGx.png" height="" width="600px">
Changez là quand même, le site se chargera de l'affichage

2021-05-20 12:30 UTC, LukeSkywalkerDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Il s'agit principalement de réseaux sociaux, de plateformes de streaming ainsi que de jeux. Ces connexions sont officielles, et ne sont pas à confondre avec les [applications tierces](https://discord
Je l'ai modifié.

2021-05-22 19:27 UTC, IchiiDev requested changes
Faites attention aux instructions

2021-05-22 19:27 UTC, IchiiDev commented on parametres-compte/connexions-compte/connexion-officielle.md
> +<img alt="Affichage de la connexion sur le profil" src="https://i.discord.fr/dGx.png" height="" width="600px">
Encore une fois, merci de changer cette syntaxe

2021-05-23 07:48 UTC, LukeSkywalkerDev commented
je l'ai modifié

2021-05-23 10:40 UTC, IchiiDev approved these changes
LGTM, je vais merge ta pull request

2021-05-23 10:40 UTC, merged

2021-07-28 15:47 UTC, DanaliethPantheus reviewed
Corrections et reformulations

2021-07-28 15:47 UTC, DanaliethPantheus commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Discord propose aux utilisateurs de relier et de synchroniser leur compte à de mutliples sites.
"multiples" et pas "mutlipes" (inversion du T et du L)

2021-07-28 15:47 UTC, DanaliethPantheus commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Il s'agit principalement de réseaux sociaux, de plateformes de streaming ainsi que de jeux. Ces connexions sont officielles, et ne sont pas à confondre avec les [applications tierces](https://discord
"ainsi que de **plateformes** de jeux

Sinon on ne comprend pas que tu fais toujours référence aux plateformes, comme précédemment.

2021-07-28 15:47 UTC, DanaliethPantheus commented on parametres-compte/connexions-compte/connexion-officielle.md
> + - La plateforme de jeu Blizzard, [Battle.net](https://blizzard.com).
plateforme de jeu**x** (au pluriel)

2021-07-28 15:47 UTC, DanaliethPantheus commented on parametres-compte/connexions-compte/connexion-officielle.md
> + Chaque connexion se configure en cliquant sur l'icone de la plateforme de son choix. Une fois cela fait, l'utilisateur devra accepter la synchronisation entre la plateforme et Discord. Puis, une foi
"Puis, une fois synchronisée avec succès" c'est redondant. Je supprimerais le "puis" et je mettrais une majuscule à "Une fois [...]. Je dirais même, pour que ça moins répétitif, qu'on peut remplacer "Une fois synchronisée avec succès" par "Lorsqu'elle sera synchronisée avec succès, la connexion s'affichera [...]"

Je rajouterais aussi une virgule après "ainsi que sur son profil".
Il faut contracter "si il souhaite" en "s'il souhaite"

2021-07-28 15:47 UTC, DanaliethPantheus commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Les utilisateurs disposent de la possibilité de désactiver l'affichage de la connexion sur votre profil en dé-sélectionnant l'icône ✅ :
"sur **leur** profil" (à la place de "votre profil")

2021-07-28 15:47 UTC, DanaliethPantheus commented on parametres-compte/connexions-compte/connexion-officielle.md
> + Chaque connexion se configure en cliquant sur l'icone de la plateforme de son choix. Une fois cela fait, l'utilisateur devra accepter la synchronisation entre la plateforme et Discord. Puis, une foi
ic**ô**ne (accent circonflexe pour respecter la même orthographe dans tout l'article)

2021-07-28 15:47 UTC, DanaliethPantheus commented on parametres-compte/connexions-compte/connexion-officielle.md
> +Il est par ailleurs possible de supprimer à tout moment la connexion dans l'onglet "Connexions" des paramètres de l'utilisateur, en cliquant simplement sur la petite croix :
"de supprimer à tout moment **une** connexion dans l'onglet" (remplacer "la" par "une" car on ne parle pas d'une connexion en particulier, mais de n'importe laquelle)

2021-07-28 15:47 UTC, DanaliethPantheus commented on parametres-compte/connexions-compte/connexion-officielle.md
> + - Le site d'hébergement de code source [Github](https://github.com).
- Le site d'hébergement et de gestion de développement de logiciels [Github](https://github.com).

(pour être plus précis, mais c'est sans doute du chipotage)

2021-08-20 19:30 UTC, PetitPotiron commented on parametres-compte/connexions-compte/connexion-officielle.md
> + - Le site d'hébergement de code source [Github](https://github.com).
On peut aussi dire que c'est un réseau social pour les développeurs, qui leur permet de donner un libre accès à leur code dans le monde entier ainsi que de gérer les versions de leurs logiciels et applications.

2021-08-20 19:37 UTC, PetitPotiron commented on parametres-compte/connexions-compte/connexion-officielle.md
> + - Le site d'hébergement de code source [Github](https://github.com).
Bonjour,
Merci d'ouvrir une nouvelle pull request avec votre propre fork, les changements ayant été approuvés.

2021-08-20 19:39 UTC, PetitPotiron commented on parametres-compte/connexions-compte/connexion-officielle.md
> + - Le site d'hébergement de code source [Github](https://github.com).
@DanaliethPantheus
Bonjour,
Merci d'ouvrir une nouvelle pull request avec votre propre fork, les changements ayant été approuvés.