Nouveaux articles et nouvelle catégorie
discordfr/wiki pull request #86
Opened 2021-06-15 06:45 UTC by PetitPotiron

**Quel est votre identifiant Discord ?**<br/> 
Entrez votre ID ici
715826047949471785

**Décrivez rapidement vos ajouts ou changements**<br/>
J'ai ajouté un article expliquant ce qu'est un bot, et comment en faire un, et un autre concernant la présence riche.

2021-06-15 09:14 UTC, BenNotix requested changes

2021-06-15 09:14 UTC, BenNotix commented on developers/bots.md
> +Rendez-vous sur [cette page](https://discord.com/developers/applications), vous aurez un écran à peu près similaire à celui-ci :
Utilisez une formulation informative (comme sur les autres articles déjà publiés sur le wiki).

2021-06-15 09:14 UTC, BenNotix commented on developers/bots.md
> +- Bonne Chance !
Utilisez une formulation informative (comme sur les autres articles déjà publiés sur le wiki).

2021-06-15 09:14 UTC, BenNotix commented on developers/bots.md
> +---
Pour créer un article, merci d'ouvrir une issue pour en demander la création.

2021-06-15 09:14 UTC, BenNotix commented on developers/intro.md
> +Peu importe où vos jeux prennent vie, ils devraient avoir une expérience de première classe chez Discord. L'activité riche est la voie pour faire de ce rêve une réalité! Nous sommes las d'échanger de
Utilisez une formulation informative (comme sur les autres articles déjà publiés sur le wiki).

2021-06-15 09:14 UTC, BenNotix commented on developers/intro.md
> +---
Pour créer un article, merci d'ouvrir une issue pour en demander la création.

2021-06-15 09:14 UTC, BenNotix commented
Bonjour !
Pour commencer, j'aimerais vous informer que l'ajout d'article sur le wiki est un peu plus complexe que ce qui en à l'air. C'est pourquoi, nous devons prendre le temps d'en discuter en interne. Pour demander la création d'un article, je vous invite à ouvrir une [issue](https://github.com/discordfr/wiki/issues) en formulant votre demande. Par la suite, si votre demande est acceptée, nous créerons un fichier .md que vous pourrez modifier par la suite.

De plus, dans vos articles, vous devez utiliser une formulation informative, il ne faut donc pas vous adresser directement au lecteur (referez vous aux articles déjà publiés).
Je vois également que vous avez ajouté des images. Vous devez les intégrer à un article, dans un fichier markdown (.md), elles ne doivent pas être seules.

2021-06-15 09:14 UTC, closed without merging

2021-06-16 13:04 UTC, PetitPotiron commented
Merci infiniment de m'avoir expliqué comment contribué, je n'avais pas très bien compris 😅