Update profil.md
discordfr/wiki pull request #89
Opened 2021-06-29 10:10 UTC by SlurpImperor

Ajout de The Wolfy image changer et 2 lignes ajoutées :  6 et 7

**Quel est votre identifiant Discord ?**<br/> 
Entrez votre ID ici

**Décrivez rapidement vos ajouts ou changements**<br/>
Entrez votre description ici

2021-06-29 14:16 UTC, IchiiDev commented
Bonjour, merci de suivre la template de pull request et inclure votre ID Discord.

2021-07-03 14:46 UTC, SlurpImperor commented
Ichii c'est bon tu j'ai modif : )

2021-07-03 15:54 UTC, IchiiDev requested changes
Beaucoup de choses à revoir

2021-07-03 15:54 UTC, IchiiDev commented on parametres-compte/personnalisation-compte/profil.md
> +**6.** Le " about me " (à propos de moi) permet de vous décrire sur votre profil discord.
Merci de ne pas vous adresser aux lecteurs directement pour suivre la constance de l'article.

2021-07-03 15:54 UTC, IchiiDev commented on parametres-compte/personnalisation-compte/profil.md
> +**7.** La bannière de profil permet de mettre un GIF (1O MB) ou une image en PNJ, PNG avec les dimensions suivantes : 600x240, discord nitro boost es nécessaire pour cette option !
Vous être trop vague, la fonctionnalité permet de mettre où le GIF ou l'image ?
Corrigez, PNJ n'est pas une extension valide.
Revoyez l'orthographe de cette ligne.

2021-07-14 07:40 UTC, IchiiDev commented
Dernier rappel avant la clôture de votre Pull Request

2021-07-16 16:28 UTC, closed without merging