Ajout mode développeur et son utilité
discordfr/wiki pull request #90
Opened 2021-07-06 16:18 UTC by capucine19

**Quel est votre identifiant Discord ?**<br/> 
Entrez votre ID ici : 422346993109827594

**Décrivez rapidement vos ajouts ou changements**<br/>
Entrez votre description ici : Ajout de comment utiliser et avoir le mode développeur.

2021-07-07 11:15 UTC, IchiiDev requested changes
Merci de garder une syntaxe informative plus que didactique, vous vous adressez dans votre article directement au lecteur, ce qui contraste avec la formulation adoptée dans le reste du wiki.

2021-07-07 19:39 UTC, capucine19 commented
modification de la syntaxe  ✅

2021-07-08 19:47 UTC, IchiiDev requested changes
Votre article n'est que trop peu exhaustif, vous ne rentrez pas assez dans les détails de ce qu'active le mode développeur. De plus, merci de garder une syntaxe neutre et globalement correcte dans votre rédaction (eg: L'introduction n'est que trop peu travaillée et aborde maladroitement le sujet, entre autres). Ne gardez pas une approche tutorielle, Wikipédia ne vous expliquera pas comment fabriquer de la nitroglicéryne mais plutôt en quoi ça consiste 👍

2021-07-16 16:29 UTC, IchiiDev commented
Dernier rappel avant la fermeture de votre Pull Request

2021-07-19 15:24 UTC, closed without merging