Update salons-textuels.md
discordfr/wiki pull request #95
Opened 2021-07-15 20:34 UTC by SladTech

**Quel est votre identifiant Discord ?**<br/> 
397839635663028235

**Décrivez rapidement vos ajouts ou changements**<br/>
J'ai ajouté dans la page salons textuels l'option "Salon des annonces".

2021-07-16 16:33 UTC, IchiiDev requested changes
Trop de fautes à revoir, faites attention aux terminaisons en -er et -é. Faites également attention aux accents qui manquent sur certaines lettres.
Merci de ne pas expliquer la marche à suivre, wiki != tutoriel
Ne vous adressez pas directement au lecteur, adoptez une écriture neutre.

2021-08-05 17:41 UTC, DanaliethPantheus approved these changes
Correction orthographe et tournures de phrases.
Révision du format des images !

2021-08-05 17:41 UTC, DanaliethPantheus commented on interface/salon-textuel/salons-textuels.md
> +Il est possible d'activé la fonctionalité "Salon des annonces", celle si permet a la communauté de suivre via leurs serveurs les messages envoyé dans le salon en question.
d'activ**er**

**à** la communauté

les messages envoyé**s**

2021-08-05 17:41 UTC, DanaliethPantheus commented on interface/salon-textuel/salons-textuels.md
> +Pour activé celle ci, il suffit d'activé le mode communautaire sur votre serveur, puis allée dans les parametre du salon en question afin d'activé l'option "Salon des annonces"
activ**er**
celle-ci (trait d'union)

il suffit d'activ**er**

mode communautaire ? Ou activer la Communauté comme il est écrit sur les onglets, les boutons, etc. ?

puis all**er**

**paramètres** (accent et pluriel)

afin d'activ**er**

2021-08-05 17:41 UTC, DanaliethPantheus commented on interface/salon-textuel/salons-textuels.md
> +Une fois cela fait, les membres de votre serveurs pourrons suivre le salon en question et voir les messages publié dans leurs serveurs.
de votre serveur (pas de s)

pourron**t**

publié**s**

De plus, je ne pense pas que ce soit judicieux d'écrire "leurs serveurs" sachant que l'option ne touche qu'un seul serveur à chaque fois qu'on clique, et qu'on ne peut pas, à ma connaissance, faire un multi-choix pour les annonces. Donc dans tout le fichier, à chaque fois que tu écris "leurs serveurs" au pluriel, je te suggère de le remettre au singulier.

2021-08-05 17:41 UTC, DanaliethPantheus commented on interface/salon-textuel/salons-textuels.md
> +<img src="https://imgur.com/a/MmoIFFB" width="650" height="" />
Toutes les images sont à refaire dans le bon format

2021-08-14 20:30 UTC, closed without merging