Update and rename suppression.md to suppression-serveur.md
discordfr/wiki pull request #96
Opened 2021-07-15 22:09 UTC by MaxenceGu21

Cette page concerne la suppression d'un serveur discord. Je n'ai rien modifié de particulier, car cette page a été créée, mais n'a pas été remplie, je me suis donc occupé de la compléter.

**Quel est votre identifiant Discord ?**<br/> 
864423158806347796

**Décrivez rapidement vos ajouts ou changements**<br/>
- [Ajout]: Etapes à suivre pour supprimer un serveur discord.

2021-07-16 16:37 UTC, IchiiDev requested changes
Beaucoup de choses à revoir: 
- Ne renommez pas les pages sans l'accord d'un reviewer au préalable.
- Ne vous adressez pas au lecteur, gardez une rédaction neutre.
- La hierarchie des titres n'est pas respectée et ils sont utilisés n'importe comment.
- Ne prenez pas l'approche d'un tutoriel, restez plus informatifs que didactique.

2021-07-16 17:44 UTC, MaxenceGu21 commented
**Modification de l'article.**
- Page renommée comme elle l'était à la base.
- Utilisation d'une réaction neutre.
- Revue complète de la mise en page.

2021-07-17 09:20 UTC, IchiiDev requested changes
Encore plusieurs choses à revoir, faites attention à la mise en forme des articles et ne supprimez rien qui aurait été ajouté par un membre de l'équipe (métadonnées).

2021-07-17 09:20 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/suppression.md
> ----
Ces métadonnées sont impératives, merci de ne les retirer sous aucun prétexte.

2021-07-17 09:20 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/suppression.md
> +# Suppression d'un serveur discord
Ce titre n'est pas nécéssaire.

2021-07-17 09:20 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/suppression.md
> +### Qu'est qu'une suppression d'un serveur discord?
Merci de respecter la hiérarchie des titres et de commencer à partir de H2

2021-07-17 09:20 UTC, IchiiDev commented on configuration-serveur/configuration-serveur/suppression.md
> +![Procédure à suivre pour supprimer un serveur discord](https://user-images.githubusercontent.com/87481394/125986314-ddc4f4c9-8002-4a69-a1ee-bceee76d6b7c.gif)
Ces étapes sont trop floues ou superflues, préférez expliquer où trouver la fonction de suppréssion plutôt que de maladroitement expliquer des étapes qui tombent sous le sens.

2021-07-17 10:16 UTC, MaxenceGu21 commented
**Modification de l'article.**
- Ajout de la métadonnées.
- Suppression du titre principal.
- Démarrage de tous les titres en H2.
- Revenue des étapes de suppression.

2021-07-29 19:59 UTC, IchiiDev requested changes
On y est presque, il faut malgré tout revoir la formulation de votre partie "Comment supprimer un serveur Discord?". Ne préférez pas une liste d'étape, faites plutôt des phrases génériques expliquant où se trouvent les boutons et que nécéssite la suppression de serveur.

2021-07-30 11:10 UTC, MaxenceGu21 commented
**Modification de l'article.**
- Revue de la formulation utilisée.

2021-07-30 14:47 UTC, IchiiDev approved these changes
Article valide, merci beaucoup !

2021-07-30 14:47 UTC, merged