Update banniere.md
discordfr/wiki pull request #98
Opened 2021-07-16 14:20 UTC by MaxenceGu21

Cette page ne contenait rien à la base. J'ai donc complété la page pour y ajouter les informations et les étapes nécessaires à la compréhension de la fonctionnalité: Bannière de profil.

**Quel est votre identifiant Discord ?**<br/> 
864423158806347796

**Décrivez rapidement vos ajouts ou changements**<br/>
- [Ajout]: Présentation de la fonctionnalité: Bannière de profil.
- [Ajout]: Etapes à suivre pour mettre une bannière à son profil.

2021-07-19 09:27 UTC, BenNotix requested changes

2021-07-19 09:27 UTC, BenNotix commented on parametres-compte/personnalisation-compte/banniere.md
> ----
Merci de ne pas supprimer le tableau contenant les informations permettant au site de fonctionner. 
N'oubliez pas de lire les instructions avant de publier un pull request...

2021-07-19 09:27 UTC, BenNotix commented on parametres-compte/personnalisation-compte/banniere.md
> +- Etape 1: Cliquez sur le bouton "Paramètres utilisateur".
Merci d'utiliser une formulation informative (pas de vouvoiements). 
Vous devez suivre le même modèle que tous les autres articles.

2021-07-19 09:27 UTC, BenNotix commented on parametres-compte/personnalisation-compte/banniere.md
> +- Etape 2: Cliquez sur le bouton "Profil d'utilisateur".
Merci d'utiliser une formulation informative (pas de vouvoiements). 
Vous devez suivre le même modèle que tous les autres articles.

2021-07-19 09:27 UTC, BenNotix commented on parametres-compte/personnalisation-compte/banniere.md
> +- Etape 3: Ajoutez votre bannière.
Merci d'utiliser une formulation informative (pas de vouvoiements). 
Vous devez suivre le même modèle que tous les autres articles.

2021-07-19 09:51 UTC, MaxenceGu21 commented
**Modification de l'article.**
- Ajout des informations permettant au tableau de fonctionner.
- Utilisation d'une réaction neutre.
- Revenue de la mise en forme de l'article.

2021-07-20 08:34 UTC, BenNotix approved these changes

2021-07-20 08:34 UTC, merged

2021-08-06 13:53 UTC, DanaliethPantheus reviewed
Corrections diverses

2021-08-06 13:53 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/banniere.md
> +La bannière de profil est accessible uniquement aux utilisateurs titulaires d'un nitro boost. Le nitro classic n'inclut pas la bannière de profil.
[...] titulaires d'un **abonnement Nitro**. Le **N**itro **C**lassic n'inclut [...]

2021-08-06 13:53 UTC, DanaliethPantheus commented on parametres-compte/personnalisation-compte/banniere.md
> +- Cliquer sur le bouton "Profil d'utilisateur".
remplacer _le bouton_ par **l'onglet**