Update threads.md
discordfr/wiki pull request #99
Opened 2021-07-16 19:07 UTC by Karal0001

**Quel est votre identifiant Discord ?**<br/> 
381574094316896258

**Décrivez rapidement vos ajouts ou changements**<br/>
J'ai eu du mal avec les permissions donc je n'ai pas pu compléter la dernière section

2021-07-17 10:18 UTC, IchiiDev requested changes
Certaines choses sont à revoir

2021-07-17 14:15 UTC, Karal0001 commented on interface/salon-textuel/threads.md
> + - NSFW : Un thread est configurer comme NSFW (Not Safe For Work) si son salon parent l'est, apparaît alors un message qui demande à l'utilisateur de confirmer qu'il a bien 18 ans car certaines image
Je me suis appuyé sur l'article [des salons textuels](https://discord.fr/wiki/interface/salon-textuel/salons-textuels/) donc il faudrait faire la modification là-haut

2021-07-29 19:45 UTC, IchiiDev requested changes
Encore des choses à revoir, un paragraphe complet sur l'archivage des threads serait le bienvenu. Il faudrait aussi parler de la suppression de Threads.

2021-07-29 19:45 UTC, IchiiDev commented on interface/salon-textuel/threads.md
> + - Permissions du thread : A COMPLETER
Les permissions sont déjà notées plus haut, cette partie n'est pas nécéssaire

2021-07-29 19:45 UTC, IchiiDev commented on interface/salon-textuel/threads.md
> + - NSFW : Un thread est configuré comme NSFW (Not Safe For Work) si son salon parent l'est. Un message apparaît pour demander à l'utilisateur de confirmer qu'il a bien 18 ans car certaines images/lie
L'erreur faite concernant les salons NSFW sera corrigée, notez ici que le contenu NSFW ne correspond pas qu'aux contenu sexuellement explicite mais également à tout média ou sujet potentiellement sensibles, pouvant heurter les personnes non-averties et les mineurs.

2021-07-29 19:45 UTC, IchiiDev commented on interface/salon-textuel/threads.md
> +Ce paramètre permet de choisir le temps sans activé.
Formulation incorrecte, je propose "temps d'inactivité maximum avant l'archivage automatique du Thread."

2021-08-05 17:33 UTC, DanaliethPantheus requested changes

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +- Utiliser des fils privés : possibilité créer des threads privés en plus des avantages de la permission au-dessus.
possibilité **de** créer des threads privés
ci-dessus (à la place de _au-dessus_)

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +- Gérer les fils : capacité e'activer le mode lent, de supprimer et d'archiver/de désarchiver les threads.
d'activer (à la place de _e'activer_)

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +- Gérer les fils : capacité e'activer le mode lent, de supprimer et d'archiver/de désarchiver les threads.
d'archiver/désarchiver (pas de répétition du _de_)

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +Afin de créer un salon thread sur un serveur, il faut avoir une des permissions suivantes : "Utiliser des fils publics" ; "Utiliser des fils privés" ; "Gérer les fils" . Les threads, tout comme salon
Les threads, tout comme **les** salons textuels

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +Contrairement aux noms de salons textuels il est possible de mettre des espaces et majuscules.
virgule après _salons textuels_

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +Contrairement aux noms de salons textuels il est possible de mettre des espaces et majuscules.
remplacer _de_ par _d'y_ OU ALORS terminer la phrase par "_dans le nom_" (ou un truc du style, sinon il manque quelque chose à la phrase).

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +Le mode lent permet de limiter le nombre de messages par utilisateur sur un interval, à l'instar du même paramètre sur les salons classiques. Les utilisateurs avec la permission "Gérer les messages"
interval**le**

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +Le mode lent permet de limiter le nombre de messages par utilisateur sur un interval, à l'instar du même paramètre sur les salons classiques. Les utilisateurs avec la permission "Gérer les messages"
Pas sûr que les gens savent ce que signifie "à l'instar de". Plus sobrement, on pourrait dire "comme le paramètre" ou "tout comme le paramètre"

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +Un thread est archivé automatiquement après le temps avant archivage défini ou bien manuellement par un membre qui a la permission "Gérer les Threads" ou son par le créateur du thread.
après le temps avant archivage défini, c'est compliqué à comprendre

Remplacer par un truc du style : "Un thread est automatiquement archivé une fois le temps avant archivage écoulé, ou bien manuellement [...]

La suite de la phrase contient une coquille : ou **son** par le créateur (supprimer _son_)

2021-08-05 17:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> + - NSFW : Un thread est configuré comme NSFW (Not Safe For Work) si son salon parent l'est. Un message apparaît pour demander à l'utilisateur de confirmer qu'il a bien 18 ans car certaines images/lie
[...] car **certains liens/images/contenus du** thread peuvent [...]

2021-08-06 13:31 UTC, Karal0001 commented on interface/salon-textuel/threads.md
> +Un thread est archivé automatiquement après le temps avant archivage défini ou bien manuellement par un membre qui a la permission "Gérer les Threads" ou son par le créateur du thread.
Je n'ai pas trouvé de meilleur formulation qui inclus le fait que le temps avant archivage puisse être défini

2021-08-06 13:33 UTC, DanaliethPantheus commented on interface/salon-textuel/threads.md
> +Un thread est archivé automatiquement après le temps avant archivage défini ou bien manuellement par un membre qui a la permission "Gérer les Threads" ou son par le créateur du thread.
Que penses-tu de ça : "Un thread est automatiquement archivé une fois que le temps avant archivage défini est écoulé, ou qu'il est archivé manuellement par un utilisateur ayant la permission "Gérer les Threads", ou par le créateur du thread lui-même."

2021-08-06 14:01 UTC, Karal0001 commented on interface/salon-textuel/threads.md
> +Un thread est archivé automatiquement après le temps avant archivage défini ou bien manuellement par un membre qui a la permission "Gérer les Threads" ou son par le créateur du thread.
J'ai un peu modifié et ça donne ça : "Un thread est automatiquement archivé une fois que le temps avant archivage défini est écoulé ou si il est archivé manuellement par un utilisateur ayant la permission "Gérer les Threads", ou par le créateur du thread lui-même."
La répétition du "ou" me gêne un peu quand même mais je pense que cette tourne reste correct

2021-08-28 09:12 UTC, Karal0001 commented
Je viens de revérifier toutes les demandes de changements et je ne vois toujours pas ce que j'ai oublié de modifie

2021-08-28 11:38 UTC, IchiiDev requested changes

2021-08-28 13:46 UTC, Karal0001 commented on interface/salon-textuel/threads.md
> +- Gérer les fils : capacité e'activer le mode lent, de supprimer et d'archiver/de désarchiver les threads.
Je viens de mettre la section des permissions en bas de la page, pour ce qui est du reste je l'avais déjà changé et il apparait avec les modification de mon coté

2021-09-05 09:56 UTC, IchiiDev approved these changes
LGTM 👍

2021-09-05 09:57 UTC, merged